; ============================================================================
; UnoDOS / Sega Master System — milestones 1-3.
; ============================================================================
; The FIRST UnoDOS port built fresh on the contract-driven + greenfield-window
; architecture (CONTRACT-ARCH §13). Bare-metal Z80 @ 3.58 MHz on the Sega VDP
; 315-5124 (Mode 4, 256x192 = 32x24 cells, 4bpp tiles, CRAM palette), 8 KB work
; RAM, the Sega mapper, the standard control pad. Built with sjasmplus into a
; plain 32 KB .sms cartridge image.
;
; M1: boot to a rendered desktop (title bar + labelled icon grid).
; M2: VBlank-driven cooperative loop, a hardware-sprite cursor steered by the
;     d-pad, the Contract event queue, and a tile window manager (create / draw
;     / focus-raise / drag / close, z-ordered) reached by clicking icons.
; M3: the app sweep — SysInfo, Clock (live), Notepad, Files, Theme (re-themes
;     CRAM live) with real content; the remaining icons open framed placeholder
;     windows. Apps tick cooperatively each frame (the COOP scheduler floor).
;
; Display model (mirrors the Genesis/SNES tile-VDP cousins): everything composes
; on the name table as (tile) cells snapped to the 8px grid; the four UnoDOS
; theme colours live in CRAM; the cursor floats above as sprite 0. Per the
; PORT-SPEC §6 audit rules the VBlank ISR only updates state (ticks + flag); the
; main loop owns every VDP access.
;
; Verification: build the AUTOTEST variant (-DAUTOTEST=1) to drive a scripted
; pad sequence into the same input path so a single screenshot proves the WM —
; the kernel simulates the pad, nothing is faked.
;
; Contract-owned (CONTRACT-ARCH Phase 4): screen geometry + window-entry /
; event-queue layout are generated by unogen from unodef/unodef.toml ([world.sms]).
; ============================================================================

    include "../unodef/gen/sms/sys_gen.inc"    ; SCRW/SCRH/SCRCOLS/SCRROWS, W*, EV_*, MAXWIN
    include "../unodef/gen/z80/unodef.inc"      ; the full Contract surface (SYS_*, enums)

; ---------------------------------------------------------------- hardware
VDP_DATA    EQU $BE
VDP_CTRL    EQU $BF
PORT_DC     EQU $DC                 ; controller port A (active low)
NAME_BASE   EQU $3800               ; tilemap base in VRAM
SAT_BASE    EQU $3F00               ; sprite attribute table
RAM_TOP     EQU $DFF0               ; stack top (8 KB RAM $C000-$DFFF)

; pad bits (active-high after we invert PORT_DC)
PAD_U       EQU $01
PAD_D       EQU $02
PAD_L       EQU $04
PAD_R       EQU $08
PAD_B1      EQU $10                 ; trigger 1 = click / select
PAD_B2      EQU $20                 ; trigger 2 = close topmost

; ---------------------------------------------------------------- RAM vars
v_ticks     EQU $C000               ; word: VBlank tick counter
v_vbl       EQU $C002
v_pad       EQU $C003
v_pad_prev  EQU $C004
v_pad_edge  EQU $C005
v_curx      EQU $C006               ; cursor x (pixels)
v_cury      EQU $C007               ; cursor y (pixels)
v_held      EQU $C008               ; frames a direction has been held (accel)
v_dirty     EQU $C009               ; non-zero -> redraw the whole scene
v_sel_icon  EQU $C00A
v_drag      EQU $C00B               ; dragging slot, $FF = none
v_drag_ox   EQU $C00C               ; drag grab offset (cells)
v_drag_oy   EQU $C00D
v_zcount    EQU $C00E
v_theme_sel EQU $C00F
v_frac      EQU $C010               ; clock: frames within the current second
v_ss        EQU $C011
v_mm        EQU $C012
v_hh        EQU $C013
v_last_ss   EQU $C014               ; clock: last second drawn
v_ev_head   EQU $C015
v_ev_tail   EQU $C016
v_auto_idx  EQU $C017               ; AUTOTEST: script cursor
v_auto_tmr  EQU $C018               ; AUTOTEST: frames left on current step
dp_col      EQU $C019               ; draw params for fill_cells
dp_row      EQU $C01A
dp_w        EQU $C01B
dp_h        EQU $C01C
dp_tile     EQU $C01D
hit_col     EQU $C01E               ; hit-test point (col/row), survives win_ptr
hit_row     EQU $C01F
clk_str     EQU $C020               ; "HH:MM:SS",0  (9 bytes -> $C028)
la_proc     EQU $C029               ; launch/create scratch (must be RAM, not ROM)
la_i        EQU $C02A
oc_slot     EQU $C02B               ; on_click: slot under cursor
dr_slot     EQU $C02C               ; redraw: current z slot
ai_pad      EQU $C02D               ; AUTOTEST: pad value for the current step
th_dig      EQU $C02E               ; theme: preset digit string (2 bytes)
event_q     EQU $C030               ; EVQ_SIZE*3 = 48 bytes
zlist       EQU $C060               ; MAXWIN bytes (top..bottom is index 0..zcount-1)
wintab      EQU $C064               ; MAXWIN*WENT_SIZE = 64 bytes

; ---------------------------------------------------------------- reset
; Canonical SMS startup: jp over the RST / interrupt vectors (sjasmplus --raw
; does not pad ORG jumps, so we never ORG forward — DEFS fills the gaps).
    ORG $0000
reset:
    di
    im 1
    jp boot

    DEFS $0038-$, $00
int_handler:                        ; $0038 — VBlank (frame interrupt)
    push af
    push hl
    in a, (VDP_CTRL)                ; ack: reading the status port clears the flag
    ld hl, (v_ticks)
    inc hl
    ld (v_ticks), hl
    ld a, 1
    ld (v_vbl), a
    pop hl
    pop af
    ei
    reti

    DEFS $0066-$, $00
nmi_handler:                        ; $0066 — pause button
    retn

boot:
    ld sp, RAM_TOP
    ; Sega mapper: slots 0/1/2 -> banks 0/1/2 (code lives in banks 0-1)
    xor a
    ld ($FFFC), a
    ld ($FFFD), a
    inc a
    ld ($FFFE), a
    inc a
    ld ($FFFF), a
    ; clear 8 KB work RAM
    ld hl, $C000
    ld de, $C001
    ld bc, $1FFF
    ld (hl), 0
    ldir

    call vdp_init
    call load_palette
    call load_tiles
    call clear_names

    ; --- initial OS state ---
    ld a, 128
    ld (v_curx), a
    ld a, 96
    ld (v_cury), a
    ld a, $FF
    ld (v_drag), a
    xor a
    ld (v_zcount), a
    ld (v_theme_sel), a
    ld (v_sel_icon), a
    ld a, 1
    ld (v_dirty), a

    call redraw_all
    call display_on
    ei

main_loop:
    halt                            ; sleep until the VBlank ISR
    call read_input
    call move_cursor
    call dispatch
    call app_ticks
    call maybe_redraw
    call cursor_to_sat
    jr main_loop

; ---------------------------------------------------------------- VDP init
vdp_init:
    ld hl, vdp_regs
    ld b, vdp_regs_end - vdp_regs
    ld c, VDP_CTRL
    otir
    ret

vdp_regs:
    db $04,$80      ; R0: Mode 4
    db $80,$81      ; R1: display OFF (set up first); 8x16 sprites enabled later
    db $FF,$82      ; R2: name table base = $3800
    db $FF,$83      ; R3
    db $FF,$84      ; R4
    db $FF,$85      ; R5: sprite attribute table = $3F00
    db $FB,$86      ; R6: sprite pattern base = $0000 (so sprite tile N = our blob)
    db $00,$87      ; R7: border/backdrop = sprite-palette index 0
    db $00,$88      ; R8: horizontal scroll = 0
    db $00,$89      ; R9: vertical scroll = 0
    db $FF,$8A      ; R10: line interrupt off
vdp_regs_end:

; display on + frame interrupt + 8x16 sprites: R1 = $E2
display_on:
    ld a, $E2
    out (VDP_CTRL), a
    ld a, $81
    out (VDP_CTRL), a
    ret

; ---------------------------------------------------------------- palette
load_palette:
    xor a
    out (VDP_CTRL), a
    ld a, $C0                       ; CRAM write, address 0
    out (VDP_CTRL), a
    ld hl, palette
    ld b, 16
    ld c, VDP_DATA
    otir                            ; background palette 0..15
    ld hl, palette
    ld b, 16
    otir                            ; sprite palette 16..31 (same colours)
    ret

; ---------------------------------------------------------------- tiles
load_tiles:
    ld hl, $0000
    call vram_set_addr
    ld hl, tiles_all
    ld de, NTILES*32
lt_loop:
    ld a, (hl)
    out (VDP_DATA), a
    inc hl
    dec de
    ld a, d
    or e
    jr nz, lt_loop
    ret

; clear the full 32x28 name table to tile 0 (desktop blue)
clear_names:
    ld hl, NAME_BASE
    call vram_set_addr
    ld de, SCRCOLS*28
cn_loop:
    xor a
    out (VDP_DATA), a
    out (VDP_DATA), a
    dec de
    ld a, d
    or e
    jr nz, cn_loop
    ret

; ---- vram_set_addr: HL = VRAM address, sets the write pointer -------------
vram_set_addr:
    ld a, l
    out (VDP_CTRL), a
    ld a, h
    or $40
    out (VDP_CTRL), a
    ret

; ---- cell_addr: B=col C=row -> HL = name-table VRAM address ---------------
cell_addr:
    ld h, 0
    ld l, c
    add hl, hl
    add hl, hl
    add hl, hl
    add hl, hl
    add hl, hl                      ; row*32
    ld a, b
    add a, l
    ld l, a
    ld a, 0
    adc a, h
    ld h, a                         ; +col
    add hl, hl                      ; *2 (2 bytes/entry)
    ld de, NAME_BASE
    add hl, de
    ret

; ---------------------------------------------------------------- input
read_input:
  IFDEF AUTOTEST
    jp auto_input
  ELSE
    in a, (PORT_DC)
    cpl                             ; active-low -> active-high
    and $3F
    ld b, a                         ; new pad
    ld a, (v_pad)
    ld (v_pad_prev), a
    ld a, b
    ld (v_pad), a
    cpl
    ld c, a                         ; ~new
    ld a, (v_pad_prev)
    cpl
    and b                           ; new & ~prev = pressed edges
    ld (v_pad_edge), a
    ret
  ENDIF

; ---- move_cursor: d-pad steers the sprite cursor (with held-accel) --------
move_cursor:
    ld a, (v_pad)
    and PAD_U | PAD_D | PAD_L | PAD_R
    jr nz, mc_held
    xor a
    ld (v_held), a
    ret
mc_held:
    ld a, (v_held)
    cp 60
    jr nc, mc_speed
    inc a
    ld (v_held), a
mc_speed:
    ld a, (v_held)
    cp 24
    ld b, 1                         ; base speed
    jr c, mc_go
    ld b, 3                         ; accelerated
mc_go:
    ld a, (v_pad)
    bit 0, a                        ; up
    jr z, mc_nu
    ld a, (v_cury)
    sub b
    cp 200                          ; underflow guard (wrapped high)
    jr c, mc_su
    xor a
mc_su:
    ld (v_cury), a
mc_nu:
    ld a, (v_pad)
    bit 1, a                        ; down
    jr z, mc_nd
    ld a, (v_cury)
    add a, b
    cp 184
    jr c, mc_sd
    ld a, 184
mc_sd:
    ld (v_cury), a
mc_nd:
    ld a, (v_pad)
    bit 2, a                        ; left
    jr z, mc_nl
    ld a, (v_curx)
    sub b
    cp 248                          ; underflow guard
    jr c, mc_sl
    xor a
mc_sl:
    ld (v_curx), a
mc_nl:
    ld a, (v_pad)
    bit 3, a                        ; right
    jr z, mc_nr
    ld a, (v_curx)
    add a, b
    cp 248
    jr c, mc_sr
    ld a, 248
mc_sr:
    ld (v_curx), a
mc_nr:
    ret

; ---- cursor_to_sat: stream the cursor into sprite 0 each frame ------------
cursor_to_sat:
    ld hl, SAT_BASE                 ; Y table
    call vram_set_addr
    ld a, (v_cury)
    out (VDP_DATA), a               ; sprite 0 Y
    ld a, $D0
    out (VDP_DATA), a               ; sprite 1 Y = terminator
    ld hl, SAT_BASE + $80           ; X/tile table
    call vram_set_addr
    ld a, (v_curx)
    out (VDP_DATA), a               ; sprite 0 X
    ld a, T_CURSOR
    out (VDP_DATA), a               ; sprite 0 tile (8x16 -> uses T_CURSOR, +1)
    ret

; ============================================================================
; Dispatch: turn pad edges + drag state into WM actions and Contract events.
; ============================================================================
dispatch:
    ; --- active drag? ---
    ld a, (v_drag)
    cp $FF
    jr z, dp_nodrag
    ; still holding B1?
    ld a, (v_pad)
    and PAD_B1
    jr z, dp_drop
    call drag_move
    ret
dp_drop:
    ld a, $FF
    ld (v_drag), a
    ld a, 1
    ld (v_dirty), a
    ret
dp_nodrag:
    ld a, (v_pad_edge)
    bit 5, a                        ; B2 -> close topmost
    jr z, dp_b1
    call close_topmost
    ret
dp_b1:
    ld a, (v_pad_edge)
    bit 4, a                        ; B1 -> click
    ret z
    jp on_click

; ---- on_click: cursor cell -> window / icon ------------------------------
on_click:
    ld a, (v_curx)
    srl a
    srl a
    srl a
    ld b, a                         ; cell col
    ld a, (v_cury)
    srl a
    srl a
    srl a
    ld c, a                         ; cell row
    call find_window_at             ; -> A = slot or $FF (also sets hit_col/hit_row)
    cp $FF
    jr z, oc_desktop
    ; clicked a window: raise it, then check close box / title / content
    ld (oc_slot), a
    call raise_window               ; (A = slot; clobbers regs)
    ld a, (oc_slot)
    call win_ptr                    ; ix = entry
    ld a, (hit_row)
    cp (ix+WY)
    jr nz, oc_focus_only            ; not the title row -> content
    ; title row — close box is the last interior col (WX+WW-2)
    ld a, (ix+WX)
    add a, (ix+WW)
    sub 2
    ld b, a
    ld a, (hit_col)
    cp b
    jr nz, oc_begin_drag
    ld a, (oc_slot)
    call close_window
    ret
oc_begin_drag:
    ld a, (oc_slot)
    ld (v_drag), a
    ld a, (hit_col)
    sub (ix+WX)
    ld (v_drag_ox), a
    ld a, (hit_row)
    sub (ix+WY)
    ld (v_drag_oy), a
    ret
oc_focus_only:
    ; click in content -> post EV_MOUSE for the app (Contract event), then act
    ld a, (hit_col)
    ld d, a                         ; data low = col
    ld a, (hit_row)
    ld e, a                         ; data high = row
    ld a, EV_MOUSE
    call ev_post
    ; the Theme app consumes content clicks to cycle the palette live
    ld a, (ix+WPROC)
    cp 5
    call z, theme_cycle
    ld a, 1
    ld (v_dirty), a
    ret
oc_desktop:
    ld a, (hit_col)
    ld b, a
    ld a, (hit_row)
    ld c, a
    call icon_at                    ; B=col C=row -> A = icon or $FF
    cp $FF
    ret z
    ld (v_sel_icon), a
    call launch_app                 ; A = proc
    ret

; ---- drag_move: reposition the dragged window to follow the cursor --------
; newX = cursorCol - drag_ox, newY = cursorRow - drag_oy (clamped on-screen)
drag_move:
    ld a, (v_drag)
    call win_ptr                    ; ix = dragged entry
    ld a, (v_curx)
    srl a
    srl a
    srl a                           ; cursor col
    ld b, a
    ld a, (v_drag_ox)
    ld c, a
    ld a, b
    sub c
    jr nc, dm_x1
    xor a
dm_x1:
    ; clamp col so the window stays on screen: max = SCRCOLS - WW
    ld c, a
    ld a, SCRCOLS
    sub (ix+WW)
    cp c
    jr nc, dm_x2
    ld c, a
dm_x2:
    ld (ix+WX), c
    ; --- Y ---
    ld a, (v_cury)
    srl a
    srl a
    srl a                           ; cursor row
    ld b, a
    ld a, (v_drag_oy)
    ld c, a
    ld a, b
    sub c
    jr nc, dm_y1
    xor a
dm_y1:
    cp 1                            ; keep below the desktop title bar (row 0)
    jr nc, dm_y1b
    ld a, 1
dm_y1b:
    ld c, a
    ld a, SCRROWS
    sub (ix+WH)
    cp c
    jr nc, dm_y2
    ld c, a
dm_y2:
    ld (ix+WY), c
    ld a, 1
    ld (v_dirty), a
    ret

; ============================================================================
; Window manager (cell coordinates). z-list: zlist[0..zcount-1] bottom..top.
; ============================================================================

; ---- win_ptr: A = slot -> IX = window entry (wintab + slot*16) ------------
win_ptr:
    add a, a
    add a, a
    add a, a
    add a, a                        ; slot*16
    ld ix, wintab
    ld c, a
    ld b, 0
    add ix, bc
    ret

; ---- find_window_at: B=col C=row -> A = slot of topmost hit, or $FF -------
find_window_at:
    ld a, b
    ld (hit_col), a
    ld a, c
    ld (hit_row), a
    ld a, (v_zcount)
    or a
    jr nz, fw_go
    ld a, $FF
    ret
fw_go:
    ld e, a                         ; e = zcount (E survives win_ptr)
fw_loop:
    dec e                           ; e = current z index, top..0
    ld a, e
    ld l, a
    ld h, 0
    ld bc, zlist
    add hl, bc
    ld a, (hl)                      ; slot at this z
    call win_ptr
    ld a, (ix+WSTATE)
    or a
    jr z, fw_next
    ld a, (hit_col)
    cp (ix+WX)
    jr c, fw_next                   ; col < WX
    ld a, (ix+WX)
    add a, (ix+WW)
    dec a                           ; WX+WW-1
    ld b, a
    ld a, (hit_col)
    cp b
    jr z, fw_in_col
    jr nc, fw_next                  ; col > WX+WW-1
fw_in_col:
    ld a, (hit_row)
    cp (ix+WY)
    jr c, fw_next                   ; row < WY
    ld a, (ix+WY)
    add a, (ix+WH)
    dec a                           ; WY+WH-1
    ld b, a
    ld a, (hit_row)
    cp b
    jr z, fw_hit
    jr nc, fw_next
fw_hit:
    ld a, e
    ld l, a
    ld h, 0
    ld bc, zlist
    add hl, bc
    ld a, (hl)
    ret
fw_next:
    ld a, e
    or a
    jr nz, fw_loop
    ld a, $FF
    ret

; ---- raise_window: A = slot -> move it to the top of the z-list ----------
raise_window:
    ld b, a                         ; b = slot to raise
    ld hl, zlist
    ld a, (v_zcount)
    ld d, a                         ; d = count
    ld e, 0                         ; e = scan index
rw_find:
    ld a, (hl)
    cp b
    jr z, rw_found
    inc hl
    inc e
    ld a, e
    cp d
    jr c, rw_find
    ret                             ; not in list (shouldn't happen)
rw_found:
    ; shift entries after it down by one, then put slot on top
rw_shift:
    ld a, e
    inc a
    cp d
    jr nc, rw_top
    inc hl
    ld a, (hl)
    dec hl
    ld (hl), a
    inc hl
    inc e
    jr rw_shift
rw_top:
    ld (hl), b
    ld a, 1
    ld (v_dirty), a
    ret

; ---- close_window: A = slot -> free it + drop from the z-list ------------
close_window:
    push af
    call win_ptr
    xor a
    ld (ix+WSTATE), a               ; WIN_STATE_FREE
    pop af
    ; remove slot from zlist, compact, dec zcount
    ld b, a                         ; slot to remove
    ld hl, zlist
    ld a, (v_zcount)
    ld d, a
    ld e, 0
cw_find:
    ld a, e
    cp d
    jr nc, cw_done
    ld a, (hl)
    cp b
    jr z, cw_remove
    inc hl
    inc e
    jr cw_find
cw_remove:
    ; shift the rest left over hl
cw_shift:
    ld a, e
    inc a
    cp d
    jr nc, cw_fixcount
    inc hl
    ld a, (hl)
    dec hl
    ld (hl), a
    inc hl
    inc e
    jr cw_shift
cw_fixcount:
    ld a, (v_zcount)
    dec a
    ld (v_zcount), a
cw_done:
    ld a, 1
    ld (v_dirty), a
    ret

; ---- close_topmost: close zlist[zcount-1] if any -------------------------
close_topmost:
    ld a, (v_zcount)
    or a
    ret z
    dec a
    ld l, a
    ld h, 0
    ld de, zlist
    add hl, de
    ld a, (hl)
    jp close_window

; ============================================================================
; Events (Contract event queue): ev_post(A=type, D=data-lo, E=data-hi)
; ============================================================================
; ev_post: A=type, D=data-lo, E=data-hi  -> append at the tail (ring)
ev_post:
    push de
    push af
    ld a, (v_ev_tail)
    ld b, a
    add a, a
    add a, b                        ; tail*3
    ld e, a
    ld d, 0
    ld hl, event_q
    add hl, de
    pop af                          ; type
    ld (hl), a
    pop de                          ; data
    inc hl
    ld (hl), d
    inc hl
    ld (hl), e
    ld a, (v_ev_tail)
    inc a
    cp EVQ_SIZE
    jr c, ep_store
    xor a
ep_store:
    ld (v_ev_tail), a
    ret

; ev_get: -> A=type (0=EVENT_NONE if empty), D=data-lo, E=data-hi
ev_get:
    ld a, (v_ev_head)
    ld b, a
    ld a, (v_ev_tail)
    cp b
    jr nz, eg_have
    xor a                           ; EVENT_NONE
    ret
eg_have:
    ld a, b
    add a, a
    add a, b                        ; head*3
    ld e, a
    ld d, 0
    ld hl, event_q
    add hl, de
    ld c, (hl)                      ; type
    inc hl
    ld d, (hl)                      ; data lo
    inc hl
    ld e, (hl)                      ; data hi
    ld a, b
    inc a
    cp EVQ_SIZE
    jr c, eg_store
    xor a
eg_store:
    ld (v_ev_head), a
    ld a, c
    ret

; ============================================================================
; Desktop icons
; ============================================================================
; icon i sits at col=(i%4)*8+1, row=3+7*(i/4); a 2x2 tile block + a label row.
; icon_at: B=col C=row -> A = icon index or $FF.
icon_at:
    ld a, b
    ld (hit_col), a
    ld a, c
    ld (hit_row), a
    ld d, 0                         ; d = icon index
ia_loop:
    ld a, d
    cp NICONS
    jr nc, ia_none
    ; col0 = (d & 3)*8 + 1
    ld a, d
    and 3
    add a, a
    add a, a
    add a, a
    inc a
    ld e, a                         ; e = col0
    ; row0 = 3 + 7*(d>>2)
    ld a, d
    srl a
    srl a
    ld b, a                         ; group
    add a, a                        ; 2g
    add a, a                        ; 4g
    add a, b                        ; 5g
    add a, b                        ; 6g
    add a, b                        ; 7g
    add a, 3
    ld h, a                         ; h = row0
    ; col in [col0, col0+1]?
    ld a, (hit_col)
    cp e
    jr c, ia_next
    ld a, e
    inc a
    ld c, a
    ld a, (hit_col)
    cp c
    jr z, ia_col_ok
    jr nc, ia_next
ia_col_ok:
    ; row in [row0, row0+3]  (the 2x2 icon plus the label row)
    ld a, (hit_row)
    cp h
    jr c, ia_next
    ld a, h
    add a, 3
    ld c, a
    ld a, (hit_row)
    cp c
    jr z, ia_hit
    jr nc, ia_next
ia_hit:
    ld a, d
    ret
ia_next:
    inc d
    jr ia_loop
ia_none:
    ld a, $FF
    ret

; ---- launch_app: A = proc -> raise existing window or create from app_def -
launch_app:
    ld (la_proc), a
    ; scan for an existing window of this proc
    xor a
    ld (la_i), a
la_scan:
    ld a, (la_i)
    cp MAXWIN
    jr nc, la_create
    call win_ptr
    ld a, (ix+WSTATE)
    or a
    jr z, la_skip
    ld a, (la_proc)
    cp (ix+WPROC)
    jr nz, la_skip
    ld a, (la_i)                    ; found — raise it
    jp raise_window
la_skip:
    ld a, (la_i)
    inc a
    ld (la_i), a
    jr la_scan
la_create:
    jp win_create

; ---- win_create: build a window for proc (la_proc) from app_def_tab ------
win_create:
    ; find a free slot
    xor a
    ld (la_i), a
wc_find:
    ld a, (la_i)
    cp MAXWIN
    ret nc                          ; table full: no-op
    call win_ptr
    ld a, (ix+WSTATE)
    or a
    jr z, wc_got
    ld a, (la_i)
    inc a
    ld (la_i), a
    jr wc_find
wc_got:
    ; app_def_tab entry = proc*6 : db x,y,w,h ; dw title
    ld a, (la_proc)
    ld l, a
    ld h, 0
    add hl, hl                      ; *2
    ld d, h
    ld e, l
    add hl, hl                      ; *4
    add hl, de                      ; *6
    ld de, app_def_tab
    add hl, de                      ; hl -> def entry
    ld a, 1
    ld (ix+WSTATE), a               ; WIN_STATE_VISIBLE
    ld a, (la_proc)
    ld (ix+WPROC), a
    ld a, (hl)
    ld (ix+WX), a
    inc hl
    ld a, (hl)
    ld (ix+WY), a
    inc hl
    ld a, (hl)
    ld (ix+WW), a
    inc hl
    ld a, (hl)
    ld (ix+WH), a
    inc hl
    ld a, (hl)
    ld (ix+WTITLE), a               ; title ptr lo
    inc hl
    ld a, (hl)
    ld (ix+WTITLE+1), a             ; title ptr hi
    ; append slot to the z-list (top)
    ld a, (v_zcount)
    ld e, a
    ld d, 0
    ld hl, zlist
    add hl, de
    ld a, (la_i)
    ld (hl), a
    ld a, (v_zcount)
    inc a
    ld (v_zcount), a
    ld a, 1
    ld (v_dirty), a
    ret


; ---------------------------------------------------------------- includes
    include "wm_render.inc"         ; rendering, M3 apps, AUTOTEST script + data
    include "gen_data.inc"          ; tiles_all, palette, NTILES, T_*, NICONS

; ---------------------------------------------------------------- ROM header
    DEFS $7FF0-$, $00
    db "TMR SEGA"                   ; $7FF0 magic
    db $00,$00                      ; reserved
    db $00,$00                      ; checksum (ignored by emulators)
    db $00,$00,$00                  ; product code + version
    db $4C                          ; region=export(4), size=32KB(C)
    DEFS $8000-$, $00
