#!/usr/bin/env python3
"""Extract the kernel API (entry-point addresses) from the ld65 label dump
(build/kernel.lbl, VICE format) into build/kernel_api.inc, which every disk-
loaded app includes.  So an app assembled SEPARATELY can `jsr draw_str` etc.
and reach the kernel's actual routine - the app is linked against the kernel
purely by address (the C64 mkapi.py pattern, ld65 flavour).

ld65 -Ln emits lines like:  al 002000 .start   (al = address label).

Usage: mkapi.py <kernel.lbl> <out.inc>
"""
import sys
import re

# The kernel routines + data a disk-loaded app may call/read.  Kept stable
# across kernel builds; the app code references these as plain equates.
API = [
    # cell + glyph draw primitives
    "set_attr", "calc_gp_px", "render_glyph",
    "draw_str", "draw_char", "fill_band", "fill_cells", "fillcell",
    # number formatting -> v_numbuf
    "fmt_dec", "div16", "put2dig", "putchar",
    # window-manager hooks the apps drive
    "redraw_topmost", "repaint_all", "ent_x", "zent_x", "launch_app",
    "return_to_desktop",
    # Ensoniq DOC audio engine (kernel-resident; Music/Tracker call it)
    "snd_note", "snd_off",
    # FAT12 storage (Files/Notepad)
    "fat_read_file", "fat_save_file", "fat_list_root",
]


def main():
    lbl, out = sys.argv[1], sys.argv[2]
    addr = {}
    for line in open(lbl):
        # al 002000 .start
        m = re.match(r"^al\s+([0-9a-fA-F]+)\s+\.(\S+)", line.strip())
        if m:
            addr[m.group(2)] = int(m.group(1), 16) & 0xFFFF
    missing = [n for n in API if n not in addr]
    if missing:
        sys.exit("mkapi: kernel symbols not found: %s" % ", ".join(missing))
    with open(out, "w") as f:
        f.write("; generated by mkapi.py - kernel API entry points - do not edit\n")
        for n in API:
            f.write("%-18s = $%04X\n" % (n, addr[n]))
    print("wrote %s (%d API entries)" % (out, len(API)))


if __name__ == "__main__":
    main()
