#!/usr/bin/env python3
"""Generate iigs/gen_data.inc from the shared UnoDOS assets.

Unlike the SNES/Genesis generators (which pre-expand the font into the
console's native planar tile format), the IIGS Super Hi-Res framebuffer is
a linear 4-bits-per-pixel bitmap, so the kernel renders text by expanding
the 1-bpp 8x8 font to 4bpp at draw time.  We therefore emit the font as the
raw 1-bpp rows (bit7 = leftmost pixel) exactly as the shared source defines
it, plus the SHR UI palette (one 16-colour palette line in $0RGB words).

Usage: python iigs/mkdata.py   (from the repo root)
"""
import re

OUT = "iigs/gen_data.inc"

# ---------------- font (shared x86 8x8, ASCII 32..126) ----------------
font = []
for line in open("kernel/font8x8.asm", encoding="latin-1"):
    m = re.match(r"\s*db\s+0b([01]{8})", line)
    if m:
        font.append(int(m.group(1), 2))
assert len(font) == 95 * 8, f"font rows: {len(font)}"

# ---------------- SHR palette line 0 (the UnoDOS UI colours) -----------
# IIGS colour word = $0RGB : bits 11-8 red, 7-4 green, 3-0 blue (4 bits each),
# stored little-endian in $E1:9E00.  PORT-SPEC SS1 base scheme is blue/cyan/
# magenta/white; entries 4+ are free for chrome and later app/game content.
PAL = [
    0x000A,   # 0  desktop blue        (background)
    0x0FFF,   # 1  white               (foreground / text)
    0x00AA,   # 2  cyan                (window body / accents)
    0x0A0A,   # 3  magenta
    0x0000,   # 4  black               (outlines / shadow)
    0x0CCC,   # 5  light grey
    0x0006,   # 6  deep blue           (title-bar fill)
    0x0FF0,   # 7  yellow
    0x0088,   # 8  teal
    0x0F80,   # 9  orange
    0x00F0,   # 10 green
    0x0F00,   # 11 red
    0x0888,   # 12 mid grey
    0x044F,   # 13 sky blue
    0x0FAC,   # 14 pink
    0x0444,   # 15 dark grey
]
assert len(PAL) == 16


def byte_rows(data):
    return "\n".join("    .byte " + ",".join(f"${b:02X}" for b in data[i:i + 16])
                     for i in range(0, len(data), 16))


with open(OUT, "w", newline="\n") as f:
    f.write("; AUTO-GENERATED by iigs/mkdata.py - do not edit\n\n")
    f.write("FONT_FIRST = 32\n")
    f.write("FONT_LAST  = 126\n")
    f.write(f"FONT_GLYPHS = {len(font) // 8}\n\n")
    f.write("; shared 8x8 font, 1bpp, bit7 = leftmost pixel; 8 bytes/glyph,\n")
    f.write("; glyphs are ASCII 32..126 in order.  Kernel expands to 4bpp.\n")
    f.write("font_data:\n" + byte_rows(font) + "\n\n")
    f.write("; SHR palette line 0 (BGR? no - $0RGB) words, little-endian on disk\n")
    f.write("pal_main:\n")
    f.write("\n".join("    .word " + ",".join(f"${w:04X}" for w in PAL[i:i + 8])
                      for i in range(0, len(PAL), 8)) + "\n")

print(f"wrote {OUT}: {len(font)//8} glyphs, {len(PAL)} palette entries")
