#!/usr/bin/env python3
"""Export the kernel API for the disk-loaded Amiga apps.

The Amiga kernel is a hunk executable that LoadSeg() relocates to an unknown
address, so (unlike the 6502 ports) apps cannot link to absolute kernel
addresses. Instead the kernel publishes a fixed-address vector table (APIVEC,
see sysabi.i) holding the RUNTIME addresses of each exported routine/data
block; apps call/read through it by ordinal.

mkapi.py's job is twofold:
  1. Verify the kernel actually defines every routine/data symbol the ABI
     promises (so a stale ABI fails the build instead of crashing the guest).
  2. Emit build/kernel_api.inc with VO_<field> byte-offset equates for every
     field of the kernel 'vars' block, read straight from the kernel listing
     so the offsets can never drift from kernel.asm.

Usage: mkapi.py <kernel.lst> <out.inc>
"""
import sys, re

# routines that MUST exist in the kernel (the APIVEC routine slots fill these)
API_ROUTINES = [
    "draw_string", "draw_string_bg", "draw_window", "fill_rect",
    "clear_screen", "redraw_topmost", "zwin_ptr", "fmt_dec", "str_append",
    "rect_outline_white", "apply_theme", "gm_start", "gm_stop", "rd_entry",
    "fat_mount", "fat_list_root", "fat_read_file", "fat_find_file",
    "fat_save_file", "return_to_desktop_app", "dt_rand7",
    "notepad_open_file", "notepad_open_fat", "launch_app", "tk_stop",
]
# data blocks that MUST exist (APIVEC data slots point at these at runtime)
API_DATA = [
    "vars", "font8x8", "npstat", "theme_pal", "cop_colptr", "romdisk_tab",
    "fat_tab", "dt_board", "pm_maze", "pm_maze_tpl", "koro_notes",
    "ext_palette", "koro_count", "romdisk_count",
    "mus_notes", "mus_count", "drive_notes", "drive_count",
    "pt_canvas", "pt_stack",
]


def main():
    lst, out = sys.argv[1], sys.argv[2]
    addr = {}                                   # name -> address (any hunk)
    hunk = {}                                    # name -> hunk number
    for line in open(lst, errors="replace"):
        # listing symbol table line:  "name      00:0001234A"  (HH = hunk)
        m = re.match(r"^([A-Za-z_][A-Za-z0-9_]*)\s+(\d+):([0-9A-Fa-f]{8})\s*$", line)
        if m:
            addr[m.group(1)] = int(m.group(3), 16)
            hunk[m.group(1)] = int(m.group(2))

    missing = [n for n in API_ROUTINES + API_DATA if n not in addr]
    if missing:
        sys.exit("mkapi: kernel symbols not found (stale ABI?): "
                 + ", ".join(missing))

    # vars-block fields: every symbol in the SAME hunk as 'vars' whose address
    # is >= vars (the vars block is the tail of the data hunk; < 8 KB wide).
    vbase = addr["vars"]
    vhunk = hunk["vars"]
    fields = sorted(
        [(n, a) for (n, a) in addr.items()
         if hunk[n] == vhunk and vbase <= a < vbase + 0x2000],
        key=lambda t: t[1])

    with open(out, "w") as f:
        f.write("; generated by mkapi.py - kernel vars-block field offsets\n")
        f.write("; (VO_<field> = byte offset from the runtime &vars). DO NOT EDIT.\n")
        for n, a in fields:
            f.write("VO_%-16s equ $%X\n" % (n, a - vbase))
    print("wrote %s (%d vars fields; %d routines + %d data verified)"
          % (out, len(fields), len(API_ROUTINES), len(API_DATA)))


if __name__ == "__main__":
    main()
