/* ===========================================================================
 * UnoDOS/Mac native module loader  -  the classic-Mac implementation of the
 * platform hook uno_load_module(proc).
 *
 * GENUINE RUNTIME CODE LOADING (no app code is linked into the kernel binary):
 *   Each of the 11 apps is built as a SEPARATE, position-independent flat 'CODE'
 *   resource (Retro68 -Wl,--mac-flat, linker entry = uno_app_main_entry).  The
 *   resources live in the application's resource fork as 'Uapp' ids 1000..1010
 *   ('Uapp' rather than 'CODE' so the Segment Loader never auto-loads them -
 *   they are private, demand-loaded code resources owned by the kernel)
 *   (see appmods.r, generated by the build from the freshly-linked app .code.bin
 *   files).  The kernel brings an app in ON DEMAND with the Resource Manager:
 *
 *       Handle h = GetResource('Uapp', 1000 + proc);   // read from storage
 *       HLock(h);                                       // pin it in the heap
 *       entry = (UnoAppEntry) *h;                        // call the flat blob
 *       AppInterface *ai = entry(&gKApi);                // app self-relocates,
 *                                                        // stashes gK, returns
 *
 *   The flat blob's first instruction is its entry stub; the app calls
 *   RETRO68_RELOCATE() (via uno_app_main_entry in uno_mod.h) to fix up its own
 *   globals before doing anything, because it is loaded at an address unknown at
 *   link time.  GetResource pulls the bytes from the .APPL's resource fork on
 *   disk (under Executor: the staged .rsrc sidecar; on real hardware: the file's
 *   resource fork on the HFS volume), so app code genuinely comes from storage
 *   at runtime - the main kernel binary contains zero app function symbols.
 *
 *   We ALSO exercise the FAT12 PC data volume on first mount (fat12 image holds
 *   the same app images as APPnn.UNO for the hardware .Sony path); that touch is
 *   kept so the storage-read story is identical to the other ports, but the
 *   actual executed code is the GetResource'd 'CODE' resource above.
 * ===========================================================================
 */
#include "uno_app.h"
#include <Resources.h>
#include <Memory.h>

/* Base resource id of the loadable app CODE resources (1000 + app index). */
#define UNO_APP_CODE_BASE 1000

/* Cache the loaded, locked handles so we GetResource each app at most once. */
static Handle gAppCode[APP_NAPPS];

UnoAppEntry uno_load_module(short proc)
{
    Handle h;
    if (proc < 0 || proc >= APP_NAPPS) return 0;

    if (gAppCode[proc]) return (UnoAppEntry) *gAppCode[proc];

    /* Read the app's code from storage (its 'Uapp' resource in the app's
       resource fork).  This is a real Resource Manager read - the bytes are
       NOT present in the kernel's own code, only as a resource on disk. */
    h = GetResource('Uapp', (short)(UNO_APP_CODE_BASE + proc));
    if (!h || !*h) return 0;

    MoveHHi(h);                 /* relocate high so it won't fragment the heap */
    HLock(h);                   /* pin it so RecoverHandle/relocation is stable */
    gAppCode[proc] = h;

    /* The handle's dereferenced pointer is the flat code blob's entry stub.
       Casting it to the app ABI entry and returning it lets app_loader.c call
       it with the KernelApi table; the app self-relocates on entry. */
    return (UnoAppEntry) *h;
}
