#!/bin/sh
# UnoDOS / Game Boy build (Sharp SM83, rgbds) -> a CGB-compatible .gb ROM.
# Usage: ./build.sh           -> build/unodos.gb        (interactive)
#        ./build.sh nav        -> build/unodos_nav.gb    (AUTOTEST: directional select)
#        ./build.sh app|clock|theme|music|dostris        (AUTOTEST: launch that app/game)
set -e
cd "$(dirname "$0")"

PY="${PY:-python}"
RGBASM="${RGBASM:-/c/Users/arin/gb-tools/rgbasm.exe}"
RGBLINK="${RGBLINK:-/c/Users/arin/gb-tools/rgblink.exe}"
RGBFIX="${RGBFIX:-/c/Users/arin/gb-tools/rgbfix.exe}"

mkdir -p build
echo "[1/4] generating tiles + data from the shared assets..."
(cd .. && "$PY" gb/mkdata.py)

# AUTOTEST switches: exactly one AT_* is 1 for a test build, all 0 otherwise.
AUTOTEST=0; AT_NAV=0; AT_APP=0; AT_CLOCK=0; AT_THEME=0; AT_MUSIC=0; AT_DOSTRIS=0
OUT=build/unodos.gb
case "$1" in
  nav)     AUTOTEST=1; AT_NAV=1;     OUT=build/unodos_nav.gb ;;
  app)     AUTOTEST=1; AT_APP=1;     OUT=build/unodos_app.gb ;;
  clock)   AUTOTEST=1; AT_CLOCK=1;   OUT=build/unodos_clock.gb ;;
  theme)   AUTOTEST=1; AT_THEME=1;   OUT=build/unodos_theme.gb ;;
  music)   AUTOTEST=1; AT_MUSIC=1;   OUT=build/unodos_music.gb ;;
  dostris) AUTOTEST=1; AT_DOSTRIS=1; OUT=build/unodos_dt.gb ;;
esac

echo "[2/4] writing build/cfg.inc (AUTOTEST switches)..."
cat > build/cfg.inc <<EOF
; AUTO-GENERATED by gb/build.sh - do not edit
DEF AUTOTEST   EQU $AUTOTEST
DEF AT_NAV     EQU $AT_NAV
DEF AT_APP     EQU $AT_APP
DEF AT_CLOCK   EQU $AT_CLOCK
DEF AT_THEME   EQU $AT_THEME
DEF AT_MUSIC   EQU $AT_MUSIC
DEF AT_DOSTRIS EQU $AT_DOSTRIS
EOF

echo "[3/4] assembling kernel.asm (Sharp SM83)..."
"$RGBASM" -o build/kernel.o kernel.asm

echo "[4/4] linking + fixing (CGB-compatible, padded to 32 KB)..."
"$RGBLINK" -o "$OUT" -n build/kernel.sym -m build/kernel.map build/kernel.o
"$RGBFIX" -v -p 0xFF -c -t "UNODOS" "$OUT"
echo "done: gb/$OUT ($(wc -c < "$OUT") bytes)"
