#!/bin/sh
# UnoDOS / NES build (6502, dasm) -> iNES NROM-256 (.nes).
# Usage: ./build.sh           -> build/unodos.nes        (interactive)
#        ./build.sh nav        -> build/unodos_nav.nes    (AUTOTEST: directional select)
#        ./build.sh app        -> build/unodos_app.nes    (AUTOTEST: launch SysInfo)
#        ./build.sh clock      -> build/unodos_clock.nes  (AUTOTEST: live Clock)
#        ./build.sh theme      -> build/unodos_theme.nes  (AUTOTEST: cycle Theme)
#        ./build.sh music      -> build/unodos_music.nes  (AUTOTEST: play Music)
#        ./build.sh dostris    -> build/unodos_dt.nes     (AUTOTEST: Dostris game)
set -e
cd "$(dirname "$0")"

PY="${PY:-python}"
DASM="${DASM:-/c/Users/arin/apple2-tools/dasm.exe}"

mkdir -p build
echo "[1/4] generating CHR (font + icons + blocks) + data from the shared assets..."
(cd .. && "$PY" nes/mkdata.py)

# AUTOTEST switches: exactly one AT_* is 1 for a test build, all 0 otherwise.
AUTOTEST=0; AT_NAV=0; AT_APP=0; AT_CLOCK=0; AT_THEME=0; AT_MUSIC=0; AT_DOSTRIS=0
OUT=build/unodos.nes
case "$1" in
  nav)     AUTOTEST=1; AT_NAV=1;     OUT=build/unodos_nav.nes ;;
  app)     AUTOTEST=1; AT_APP=1;     OUT=build/unodos_app.nes ;;
  clock)   AUTOTEST=1; AT_CLOCK=1;   OUT=build/unodos_clock.nes ;;
  theme)   AUTOTEST=1; AT_THEME=1;   OUT=build/unodos_theme.nes ;;
  music)   AUTOTEST=1; AT_MUSIC=1;   OUT=build/unodos_music.nes ;;
  dostris) AUTOTEST=1; AT_DOSTRIS=1; OUT=build/unodos_dt.nes ;;
esac

echo "[2/4] writing build/cfg.inc (AUTOTEST switches)..."
cat > build/cfg.inc <<EOF
; AUTO-GENERATED by nes/build.sh - do not edit
AUTOTEST    EQU $AUTOTEST
AT_NAV      EQU $AT_NAV
AT_APP      EQU $AT_APP
AT_CLOCK    EQU $AT_CLOCK
AT_THEME    EQU $AT_THEME
AT_MUSIC    EQU $AT_MUSIC
AT_DOSTRIS  EQU $AT_DOSTRIS
EOF

echo "[3/4] assembling kernel.s (6502, 32KB PRG)..."
"$DASM" kernel.s -f3 -obuild/prg.bin -lbuild/kernel.lst -sbuild/kernel.sym

echo "[4/4] packing iNES ROM..."
"$PY" mkines.py build/prg.bin build/chr.bin "$OUT"
echo "done: nes/$OUT"
