/* ===========================================================================
 * UnoDOS/PS2 EE audio - the Sound Manager square-wave synth over audsrv.
 *
 * The portable core drives sound through the Toolbox Sound Manager: it opens
 * square-wave channels (`SndNewChannel`) and fires `noteCmd`/`quietCmd`
 * (`SndDoImmediate`) - param1 = duration in half-ms, param2 = MIDI note. On the
 * host that's a silent stub (mac_io.c); on the EE this module realises it as an
 * actual square-wave synthesiser mixed to the SPU2 via audsrv.
 *
 *   uno_audio_bringup()-load LIBSD (rom0) + the embedded audsrv.irx, bring up
 *                       audsrv (16-bit / 22050 Hz / stereo), build the MIDI->Hz
 *                       table. Runs on the shared I/O-init thread (ee_platform.c)
 *                       under the SIF lock - never the main thread, since
 *                       audsrv_init can spin forever on an emulator with no SPU2
 *                       HLE and must not block the boot.
 *   uno_audio_note()  - (called from SndDoImmediate) retrigger a channel: set
 *                       its frequency + remaining sample count. No SIF - just
 *                       shared state the pump reads.
 *   uno_audio_quiet() - silence a channel.
 *   uno_audio_pump()  - (called once per frame from uno_ee_present) top up the
 *                       audsrv ring with however many bytes are free
 *                       (`audsrv_available`, so it never blocks), synthesising +
 *                       mixing the active channels. Guarded by the shared SIF
 *                       lock so it never races the USB init thread's RPC binds.
 *
 * All audsrv SIF stays on the main thread (init + pump); the only other SIF
 * actor is the USB init thread, and the SIF lock (ee_platform.c) keeps the two
 * mutually exclusive.
 * ======================================================================== */
#include <tamtypes.h>
#include <kernel.h>
#include <sifrpc.h>
#include <loadfile.h>
#include <audsrv.h>
#include <string.h>

#include "mac_compat.h"

#include "audsrv_irx.c"      /* bin2c image, generated by the Makefile */

#define SND_FREQ   22050     /* SPU2-friendly rate; chiptune doesn't need more */
#define SND_CHANS  8         /* matches the shim's channel pool (mac_io.c)     */
#define SND_AMP    3500      /* per-voice amplitude; 8*AMP stays < 32767       */
#define BUF_FRAMES 2048      /* max stereo frames generated per pump           */

typedef struct {
    volatile int freq;       /* Hz, 0 = idle */
    volatile int remain;     /* samples left in the current note */
    unsigned     phase;      /* 32-bit phase accumulator (square = top bit) */
} AudChan;

static int     g_audio_ok;
static int     g_midi[128];                 /* MIDI note -> Hz */
static AudChan g_ch[SND_CHANS];
static short   g_buf[BUF_FRAMES * 2];        /* interleaved L/R */

/* Bring audsrv up. Called from the I/O-init thread (ee_platform.c) holding the
   SIF lock, NOT the main thread: audsrv_init spins on the SIF bus until the IOP
   audio server answers, which never happens on an emulator without SPU2 HLE, so
   it must not be allowed to block the boot. */
void uno_audio_bringup(void)
{
    int ret, i;
    float f;
    audsrv_fmt_t fmt;

    SifLoadModule("rom0:LIBSD", 0, NULL);                  /* SPU2 driver (ROM) */
    SifExecModuleBuffer(audsrv_irx, size_audsrv_irx, 0, NULL, &ret);

    if (audsrv_init() != 0) return;
    fmt.bits = 16;
    fmt.freq = SND_FREQ;
    fmt.channels = 2;
    if (audsrv_set_format(&fmt) != 0) return;
    audsrv_set_volume(MAX_VOLUME);

    /* equal-tempered scale from MIDI 0 (8.1758 Hz), each step * 2^(1/12) */
    f = 8.1757989f;
    for (i = 0; i < 128; i++) {
        g_midi[i] = (int)(f + 0.5f);
        f *= 1.0594630944f;
    }
    g_audio_ok = 1;
}

void uno_audio_note(int chan, short midi, long half_ms)
{
    int n;
    if (chan < 0 || chan >= SND_CHANS) return;
    if (midi < 0) midi = 0;
    if (midi > 127) midi = 127;
    n = (int)((half_ms * (long)SND_FREQ) / 2000);   /* half-ms -> samples */
    g_ch[chan].freq = g_midi[midi];
    g_ch[chan].remain = n;
}

void uno_audio_quiet(int chan)
{
    if (chan < 0 || chan >= SND_CHANS) return;
    g_ch[chan].remain = 0;
}

void uno_audio_pump(void)
{
    int avail, bytes, frames, i, c;

    if (!g_audio_ok) return;
    if (!uno_sif_lock_try()) return;        /* USB init thread holds SIF - skip */

    avail = audsrv_available();
    if (avail >= 4) {
        bytes = avail;
        if (bytes > (int)sizeof(g_buf)) bytes = (int)sizeof(g_buf);
        bytes &= ~3;                         /* whole stereo frames (4 bytes) */
        frames = bytes >> 2;
        memset(g_buf, 0, (size_t)bytes);

        for (c = 0; c < SND_CHANS; c++) {
            AudChan *ch = &g_ch[c];
            int rem = ch->remain, hz = ch->freq;
            unsigned ph = ch->phase, inc;
            if (rem <= 0 || hz <= 0) continue;
            inc = (unsigned)(((unsigned long long)hz << 32) / SND_FREQ);
            for (i = 0; i < frames && rem > 0; i++, rem--) {
                short s = (ph & 0x80000000u) ? SND_AMP : -SND_AMP;
                g_buf[i * 2]     = (short)(g_buf[i * 2]     + s);
                g_buf[i * 2 + 1] = (short)(g_buf[i * 2 + 1] + s);
                ph += inc;
            }
            ch->phase = ph;
            ch->remain = rem;
        }
        audsrv_play_audio((char *)g_buf, bytes);
    }

    uno_sif_unlock();
}
