/* ===========================================================================
 * UnoDOS/PS2 - USB keyboard + mouse for the EE platform (real hardware input).
 *
 * The DualShock 2 path (ee_platform.c) is icon-nav only: d-pad arrows, Cross/
 * Circle = Return, Start = Esc. This module adds the two USB HID devices the
 * PS2 actually has ports for, so the desktop is usable like the Mac it was
 * ported from - real typing into Notepad and a clickable pointer.
 *
 *   uno_usb_init()  - SifExecModuleBuffer the three IOP drivers (usbd + ps2kbd
 *                     + ps2mouse, embedded below via bin2c so the ELF is
 *                     self-contained for FreeMcBoot), then PS2KbdInit /
 *                     PS2MouseInit. Keyboard runs in RAW (USB-HID-usage) mode
 *                     so we own the full keymap incl. arrows/modifiers; mouse
 *                     runs in ABS mode clamped to the framebuffer so the driver
 *                     keeps an absolute cursor position for us.
 *   uno_usb_poll()  - drain the keyboard (HID usage -> UnoDOS key events) and
 *                     read the mouse (-> uno_set_mouse + mouseDown/Up edges).
 *                     Called once per frame alongside uno_ee_poll().
 *   uno_usb_cursor()- current pointer position + visibility, for ee_platform.c
 *                     to draw a GS overlay arrow on top of the blitted fb (the
 *                     software framebuffer is left untouched, so unodos.c's
 *                     incremental/XOR drawing is unaffected).
 *
 * Co-exists with the pad: both feed the same shim event queue, so a user can
 * use whichever is plugged in.
 * ======================================================================== */
#include <tamtypes.h>
#include <kernel.h>
#include <sifrpc.h>
#include <loadfile.h>
#include <libkbd.h>
#include <libmouse.h>
#include <ps2kbd.h>
#include <ps2mouse.h>
#include <string.h>

#include "fb.h"
#include "mac_compat.h"

/* IOP drivers embedded into the ELF (bin2c, generated by the Makefile from
   $PS2SDK iop/irx). Self-contained: no rom0/mc0 path dependency. */
#include "usbd_irx.c"
#include "ps2kbd_irx.c"
#include "ps2mouse_irx.c"

/* ---- modifier bitfield (mirrors the USB HID 0xE0..0xE7 modifier keys) ---- */
#define MOD_LCTRL  (1 << 0)
#define MOD_LSHIFT (1 << 1)
#define MOD_LALT   (1 << 2)
#define MOD_LGUI   (1 << 3)
#define MOD_RCTRL  (1 << 4)
#define MOD_RSHIFT (1 << 5)
#define MOD_RALT   (1 << 6)
#define MOD_RGUI   (1 << 7)

static volatile int g_kbd_ok;       /* set by the init thread once kbd is up */
static volatile int g_mouse_ok;     /* set by the init thread once mouse is up */
static u8   g_mods;                 /* live modifier state */
static int  g_mx = FB_W / 2;        /* cursor position (clamped to fb) */
static int  g_my = FB_H / 2;
static int  g_mouse_seen;           /* a mouse has reported at least once */
static int  g_btn_prev;             /* previous left-button state */

/* Translate a USB HID usage code to a UnoDOS (charcode, Mac keycode) pair.
   Mac keycodes match the DualShock path: arrows 0x7B/7C/7D/7E, Return 0x24,
   Esc 0x35, Backspace 0x33; printables carry code 0 (the core keys off the
   char for those). Returns 0 if the key is not one the core consumes. */
static int hid_translate(u8 hid, int shift, char *ch, short *code)
{
    *code = 0;
    if (hid >= 0x04 && hid <= 0x1D) {           /* a..z */
        char base = (char)('a' + (hid - 0x04));
        *ch = shift ? (char)(base - 'a' + 'A') : base;
        return 1;
    }
    if (hid >= 0x1E && hid <= 0x27) {           /* 1..9 0 (top row) */
        static const char un[10] = {'1','2','3','4','5','6','7','8','9','0'};
        static const char sh[10] = {'!','@','#','$','%','^','&','*','(',')'};
        *ch = shift ? sh[hid - 0x1E] : un[hid - 0x1E];
        return 1;
    }
    switch (hid) {
    case 0x28: case 0x58: *ch = 0x0D; *code = 0x24; return 1; /* Enter/KP-Enter */
    case 0x29: *ch = 0x1B; *code = 0x35; return 1;            /* Esc */
    case 0x2A: *ch = 0x08; *code = 0x33; return 1;            /* Backspace */
    case 0x4C: *ch = 0x7F; *code = 0x75; return 1;            /* Delete fwd */
    case 0x2B: *ch = 0x09; *code = 0x30; return 1;            /* Tab */
    case 0x2C: *ch = ' ';  *code = 0x31; return 1;            /* Space */
    case 0x4F: *ch = 0x1D; *code = 0x7C; return 1;            /* Right */
    case 0x50: *ch = 0x1C; *code = 0x7B; return 1;            /* Left */
    case 0x51: *ch = 0x1F; *code = 0x7D; return 1;            /* Down */
    case 0x52: *ch = 0x1E; *code = 0x7E; return 1;            /* Up */
    case 0x2D: *ch = shift ? '_' : '-';  return 1;
    case 0x2E: *ch = shift ? '+' : '=';  return 1;
    case 0x2F: *ch = shift ? '{' : '[';  return 1;
    case 0x30: *ch = shift ? '}' : ']';  return 1;
    case 0x31: *ch = shift ? '|' : '\\'; return 1;
    case 0x33: *ch = shift ? ':' : ';';  return 1;
    case 0x34: *ch = shift ? '"' : '\''; return 1;
    case 0x35: *ch = shift ? '~' : '`';  return 1;
    case 0x36: *ch = shift ? '<' : ',';  return 1;
    case 0x37: *ch = shift ? '>' : '.';  return 1;
    case 0x38: *ch = shift ? '?' : '/';  return 1;
    }
    return 0;
}

/* Bring the USB stack up. Called from the I/O-init thread (ee_platform.c) while
   it holds the SIF lock, NOT the main thread: PS2KbdInit / PS2MouseInit spin
   inside the library until each IOP driver's RPC server registers, which never
   happens on an emulator with no USB HLE, so they must not block the boot.
   On real hardware they return promptly and kbd/mouse come alive. */
void uno_usb_bringup(void)
{
    int ret;

    /* USB host + the two HID class drivers, straight from the embedded images.
       usbd must come first; the kbd/mouse drivers bind to it on load. */
    SifExecModuleBuffer(usbd_irx,     size_usbd_irx,     0, NULL, &ret);
    SifExecModuleBuffer(ps2kbd_irx,   size_ps2kbd_irx,   0, NULL, &ret);
    SifExecModuleBuffer(ps2mouse_irx, size_ps2mouse_irx, 0, NULL, &ret);

    if (PS2KbdInit() >= 0) {
        PS2KbdSetReadmode(PS2KBD_READMODE_RAW);     /* we own the keymap */
        PS2KbdSetBlockingMode(PS2KBD_NONBLOCKING);  /* never stall the frame */
        g_kbd_ok = 1;
    }
    if (PS2MouseInit() >= 0) {
        PS2MouseSetReadMode(PS2MOUSE_READMODE_ABS); /* driver keeps abs pos */
        PS2MouseSetBoundary(0, FB_W - 1, 0, FB_H - 1);
        PS2MouseSetPosition(g_mx, g_my);
        g_mouse_ok = 1;
    }
}

static void poll_kbd(void)
{
    PS2KbdRawKey rk;
    while (PS2KbdReadRaw(&rk) > 0) {
        if (rk.key >= 0xE0 && rk.key <= 0xE7) {     /* modifier key */
            u8 bit = (u8)(1 << (rk.key - 0xE0));
            if (rk.state == PS2KBD_RAWKEY_DOWN) g_mods |= bit;
            else                                g_mods &= (u8)~bit;
            continue;
        }
        if (rk.state != PS2KBD_RAWKEY_DOWN) continue;   /* fire on press */
        {
            int   shift = (g_mods & (MOD_LSHIFT | MOD_RSHIFT)) != 0;
            /* Ctrl or the Win/GUI key stands in for the Mac Command key */
            int   cmd   = (g_mods & (MOD_LCTRL | MOD_RCTRL |
                                     MOD_LGUI  | MOD_RGUI)) != 0;
            char  ch;
            short code;
            if (hid_translate(rk.key, shift, &ch, &code)) {
                Point p = { 0, 0 };
                long  msg = ((long)(code & 0xFF) << 8) | (unsigned char)ch;
                uno_post_event(keyDown, msg, p, cmd ? cmdKey : 0);
            }
        }
    }
}

static void poll_mouse(void)
{
    mouse_data md;
    if (PS2MouseRead(&md) <= 0) return;             /* no fresh sample */
    g_mouse_seen = 1;
    g_mx = md.x;
    g_my = md.y;
    if (g_mx < 0) g_mx = 0;
    if (g_mx >= FB_W) g_mx = FB_W - 1;
    if (g_my < 0) g_my = 0;
    if (g_my >= FB_H) g_my = FB_H - 1;

    {
        int   down = (md.buttons & PS2MOUSE_BTN1) != 0;   /* left button */
        Point p; p.h = (short)g_mx; p.v = (short)g_my;
        uno_set_mouse((short)g_mx, (short)g_my, (Boolean)down);
        if (down && !g_btn_prev)       uno_post_event(mouseDown, 0, p, 0);
        else if (!down && g_btn_prev)  uno_post_event(mouseUp,   0, p, 0);
        g_btn_prev = down;
    }
}

void uno_usb_poll(void)
{
    if (!g_kbd_ok && !g_mouse_ok) return;
    /* kbd/mouse reads are SIF RPC; take the shared bus lock so we never overlap
       the audio pump or a still-running USB init. Non-blocking: skip the frame
       if the bus is busy (e.g. init still binding). */
    if (!uno_sif_lock_try()) return;
    if (g_kbd_ok)   poll_kbd();
    if (g_mouse_ok) poll_mouse();
    uno_sif_unlock();
}

/* Pointer for the GS overlay (ee_platform.c). Returns 1 (visible) once a mouse
   has actually reported, so the arrow doesn't sit on screen with no device. */
int uno_usb_cursor(short *x, short *y)
{
    if (x) *x = (short)g_mx;
    if (y) *y = (short)g_my;
    return g_mouse_ok && g_mouse_seen;
}
