#!/usr/bin/env python3
"""Extract the kernel API (entry-point addresses) from the dasm symbol dump
(build/kernel.sym) into build/kernel_api.inc, which every disk-loaded app
includes. So an app assembled separately can `jsr draw_string` etc. and reach
the kernel's actual routine - the app is linked against the kernel by address.

Usage: mkapi.py <kernel.sym> <out.inc>
"""
import sys, re

# the routines a disk-loaded app may call (kept stable across kernel builds)
API = [
    "draw_char", "draw_string", "draw_name12", "draw_name12_title", "draw_dec16",
    "fill_rows", "color_fill", "dither_rect", "win_outline", "app_clear",
    "clear_bitmap", "blit_cell", "sid_click", "return_to_desktop",
    "fs_find", "fs_read", "fs_save", "fs_entry_ptr",
]


def main():
    sym, out = sys.argv[1], sys.argv[2]
    addr = {}
    for line in open(sym):
        m = re.match(r"^(\S+)\s+([0-9a-fA-F]{1,4})\s", line)
        if m:
            addr[m.group(1)] = int(m.group(2), 16)
    missing = [n for n in API if n not in addr]
    if missing:
        sys.exit("mkapi: kernel symbols not found: %s" % ", ".join(missing))
    with open(out, "w") as f:
        f.write("; generated by mkapi.py - kernel API entry points - do not edit\n")
        for n in API:
            f.write("%-20s equ $%04X\n" % (n, addr[n]))
    print("wrote %s (%d API entries)" % (out, len(API)))


if __name__ == "__main__":
    main()
