#!/usr/bin/env python3
"""Emit c64/build/font8.s from the shared UnoDOS font (kernel/font8x8.asm).

The shared font is already 8x8, one byte per row, BIT 7 = leftmost pixel -
which is exactly the C64 hi-res bitmap convention (the leftmost of a cell's
8 pixels is bit 7 of the byte). So unlike the Apple II port (which has to
re-pack to a 7px/bit-0-left layout), the C64 takes the glyph bytes verbatim.

95 glyphs, ASCII 32..126, accessed as font8 + (ch-32)*8.
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
src = os.path.join(HERE, "..", "kernel", "font8x8.asm")
out = os.path.join(HERE, "build", "font8.s")

rows = []
for line in open(src, encoding="latin-1"):
    m = re.match(r"\s*db\s+0b([01]{8})", line)
    if m:
        rows.append(int(m.group(1), 2))
assert len(rows) == 95 * 8, "font rows: %d (expected 760)" % len(rows)

os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w") as f:
    f.write("; generated by mkfont.py from kernel/font8x8.asm (verbatim) - do not edit\n")
    f.write("font8:\n")
    for g in range(0, len(rows), 8):
        f.write("\tdc.b %s\n" % ",".join("$%02X" % b for b in rows[g:g + 8]))
print("wrote %s: 95 glyphs" % out)
