#!/usr/bin/env python3
"""Generate c64/build/tables.s - the VIC-II hi-res bitmap address tables the
kernel's renderer needs (dasm dc.b).

C64 hi-res bitmap layout (VIC bank 1, $4000-$7FFF):
  - bitmap base $6000, screen-RAM (per-cell colour nibbles) base $4000.
  - the byte holding pixel (x, y) is at
        $6000 + (y>>3)*320 + (x>>3)*8 + (y&7)
    i.e. cells are 8 bytes apart horizontally, the 8 rows WITHIN a cell are
    consecutive, and stepping y across a cell boundary jumps by 320-7.
  - bit 7 of that byte is the leftmost of the 8 pixels (matches the shared
    UnoDOS font convention exactly - no bit reversal needed).
  - in standard (non-multicolour) hi-res, the two colours of a cell come
    from screen RAM: upper nibble = "1"/foreground, lower nibble = "0"/
    background. (Colour RAM at $D800 is unused in this mode.)

So the renderer works in 8x8 character cells (40 wide x 25 tall) for colour,
and in (byte-column, pixel-row) for the bitmap shapes - exactly the Apple II
port's model, just with a different address formula. The tables:

  rowbase_lo/hi[y]   $6000 + (y>>3)*320 + (y&7)   column-0 byte addr, y=0..199
  scr_lo/hi[cy]      $4000 + cy*40               screen-RAM row addr,  cy=0..24
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(HERE, "build", "tables.s")

BITMAP = 0x6000
SCREEN = 0x4000


def emit_table(f, name, values):
    f.write("%s_lo:\n" % name)
    for i in range(0, len(values), 16):
        f.write("\tdc.b %s\n" % ",".join("$%02X" % (v & 0xFF) for v in values[i:i + 16]))
    f.write("%s_hi:\n" % name)
    for i in range(0, len(values), 16):
        f.write("\tdc.b %s\n" % ",".join("$%02X" % ((v >> 8) & 0xFF) for v in values[i:i + 16]))


rowbase = [BITMAP + (y >> 3) * 320 + (y & 7) for y in range(200)]
scr = [SCREEN + cy * 40 for cy in range(25)]

os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w") as f:
    f.write("; generated by mktables.py - VIC-II hi-res bitmap address tables - do not edit\n")
    emit_table(f, "rowbase", rowbase)
    emit_table(f, "scr", scr)
print("wrote %s (rowbase[200], scr[25])" % out)
