#!/usr/bin/env python3
"""unogen — emit the per-world contract surface from unodef/unodef.toml.

CONTRACT-ARCH §3.2: unogen emits only the SHAPE of the boundary (ordinals, struct
offsets, constants, enums) — never syscall bodies, drivers, or CPU logic. One
machine-readable Contract in; the mechanical, drift-prone, hand-duplicated parts
out, per world, in that world's assembler dialect.

This is the Phase-1 MVP across the first 5 worlds (the CPU families that cover every
shipped port): x86/NASM, C core, 68000/vasm, 6502/dasm, 65816/ca65.

Usage:  python unodef/unogen.py            # emit all worlds into unodef/gen/
        python unodef/unogen.py --check    # emit + assert x86 == kernel.asm literals (trust anchor)
"""
import os, re, sys, tomllib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DEF  = os.path.join(HERE, "unodef.toml")
GEN  = os.path.join(HERE, "gen")

# ---------------------------------------------------------------------------
# Load + normalize the Contract
# ---------------------------------------------------------------------------
def load():
    with open(DEF, "rb") as f:
        return tomllib.load(f)

FIELD_RE = re.compile(r"^\s*(\w+)\s*:\s*(\w+)(?:\[(\d+)\])?\s*@(\d+)\s*(le|be)?\s*$")
TYPE_BYTES = {"u8": 1, "i8": 1, "u16": 2, "i16": 2, "u32": 4, "i32": 4}

def parse_field(s):
    m = FIELD_RE.match(s)
    if not m:
        raise ValueError("bad field: %r" % s)
    name, ty, n, off, endian = m.group(1), m.group(2), m.group(3), int(m.group(4)), m.group(5)
    if ty in ("char", "bytes"):
        size = int(n)
        cty = ("char" if ty == "char" else "uint8_t", "[%s]" % n)
    else:
        size = TYPE_BYTES[ty]
        cty = ({"u8":"uint8_t","i8":"int8_t","u16":"uint16_t","i16":"int16_t",
                "u32":"uint32_t","i32":"int32_t"}[ty], "")
    return dict(name=name, ty=ty, off=off, size=size, cty=cty)

def sysname(name):
    return "SYS_" + name.upper()

# ---------------------------------------------------------------------------
# Dialects: every world shares the SAME symbols; only the line syntax differs.
# ---------------------------------------------------------------------------
class Dialect:
    def __init__(self, comment, eq):
        self.comment, self._eq = comment, eq
    def c(self, text):  # comment line
        return "%s %s" % (self.comment, text)
    def eq(self, sym, val, hexfmt=False):
        v = ("0x%X" % val) if hexfmt else str(val)
        return self._eq(sym, v)

NASM = Dialect(";", lambda s, v: "%-26s equ %s" % (s, v))
VASM = Dialect(";", lambda s, v: "%-26s equ %s" % (s, v))
DASM = Dialect(";", lambda s, v: "%-26s EQU %s" % (s, v))
CA65 = Dialect(";", lambda s, v: "%-26s = %s" % (s, v))
Z80  = Dialect(";", lambda s, v: "%-26s EQU %s" % (s, v))   # sjasmplus / z80asm

BANNER = [
    "GENERATED by unodef/unogen.py from unodef/unodef.toml — DO NOT EDIT.",
    "The Contract (Layer 0) is the single source of truth; regenerate, don't hand-edit.",
]

# ---------------------------------------------------------------------------
# Section model: a list of (symbol, value, hexfmt, inline-comment) rows, grouped
# under headings. Shared across all asm dialects; C renders its own structs too.
# ---------------------------------------------------------------------------
def build_rows(d):
    cg   = d["callgate"]
    con  = d["contract"]
    fat  = d["const"]["fat12"]
    font = d["const"]["font"]
    scr  = d["const"]["screen"]
    pal  = d["const"]["palette"]
    structs = {s["name"]: s for s in d["struct"]}

    G = []  # list of (heading, [ (sym,val,hex,comment) ])

    G.append(("Contract / ABI", [
        ("UNO_ABI_MAJOR", con["abi_target"]["major"], False, ""),
        ("UNO_ABI_MINOR", con["abi_target"]["minor"], False, ""),
        ("SYS_COUNT",     cg["count"],                False, "number of call-gate slots (ordinals 0..N-1)"),
    ]))

    # Syscall ordinals
    rows = [(sysname(s["name"]), s["ordinal"], False,
             s["brief"] + (" [deprecated]" if s.get("deprecated") else "")
                        + (" [reserved]" if s.get("reserved") else ""))
            for s in sorted(d["syscall"], key=lambda x: x["ordinal"])]
    G.append(("Syscall ordinals (the call gate)", rows))

    # Window struct
    w = structs["win_entry"]
    wf = {f["name"]: parse_field(x) for x, f in [(x, parse_field(x)) for x in w["fields"]]}
    G.append(("Window table (struct win_entry)", [
        ("WIN_MAX_COUNT",  w["count"], False, "fixed window table size"),
        ("WIN_ENTRY_SIZE", w["size"],  False, ""),
    ] + [("WIN_OFF_" + f["name"].upper(), f["off"], False, f["ty"]) for f in wf.values()]))

    # Event struct + queue
    e = structs["event"]
    ef = [parse_field(x) for x in e["fields"]]
    G.append(("Event record (struct event)", [
        ("EVENT_ENTRY_SIZE",  e["size"],  False, "type:u8 + data:u16"),
        ("EVENT_QUEUE_COUNT", e["count"], False, "single global queue depth"),
    ] + [("EVENT_OFF_" + f["name"].upper(), f["off"], False, f["ty"]) for f in ef]))

    # File handle struct
    fh = structs["file_handle"]
    ff = [parse_field(x) for x in fh["fields"] if not f_is_reserved(x)]
    G.append(("File handle table (struct file_handle)", [
        ("FILE_MAX_HANDLES", fh["count"], False, ""),
        ("FILE_ENTRY_SIZE",  fh["size"],  False, ""),
    ] + [("FILE_OFF_" + f["name"].upper(), f["off"], False,
          f["ty"] + ("  ; owner task; 0xFF=kernel" if f["name"] == "owner" else ""))
         for f in ff]))

    # Dirent
    de = structs["dirent"]
    df = [parse_field(x) for x in de["fields"] if not f_is_reserved(x)]
    G.append(("FAT12 directory entry (struct dirent)", [
        ("DIRENT_SIZE", de["size"], False, ""),
    ] + [("DIRENT_OFF_" + f["name"].upper(), f["off"], False, f["ty"]) for f in df]))

    # .BIN header
    bh = structs["bin_header"]
    bf = [parse_field(x) for x in bh["fields"]]
    G.append((".BIN app container header (struct bin_header)", [
        ("BIN_HEADER_SIZE", bh["size"], False, "code entry begins here (0x50)"),
    ] + [("BIN_OFF_" + f["name"].upper(), f["off"], False, f["ty"]) for f in bf]))

    # FAT12 geometry — the "five places", now one block
    G.append(("FAT12 geometry (x86 1.44MB floppy; the five-places, unified)", [
        ("FAT12_BYTES_PER_SECTOR",   fat["bytes_per_sector"],   False, ""),
        ("FAT12_SECTORS_PER_CLUSTER",fat["sectors_per_cluster"],False, ""),
        ("FAT12_RESERVED_SECTORS",   fat["reserved_sectors"],   False, "within the filesystem"),
        ("FAT12_NUM_FATS",           fat["num_fats"],           False, ""),
        ("FAT12_ROOT_DIR_ENTRIES",   fat["root_dir_entries"],   False, ""),
        ("FAT12_SECTORS_PER_FAT",    fat["sectors_per_fat"],    False, ""),
        ("FAT12_FS_START_SECTOR",    fat["fs_start_sector"],    False, "OS area size / FS base"),
        ("FAT12_FAT_START",          fat["fat_start"],          False, "absolute"),
        ("FAT12_ROOT_DIR_START",     fat["root_dir_start"],     False, "absolute"),
        ("FAT12_ROOT_DIR_SECTORS",   fat["root_dir_sectors"],   False, ""),
        ("FAT12_DATA_AREA_START",    fat["data_area_start"],    False, "absolute"),
    ]))

    # Boot / OS-area layout (single-sources the "110" across boot + tools)
    if "boot_layout" in d["const"]:
        bl = d["const"]["boot_layout"]
        G.append(("Boot / OS-area layout (sums to FAT12_FS_START_SECTOR)", [
            ("BOOT_BOOT_SECTORS",   bl["boot_sectors"],   False, ""),
            ("BOOT_STAGE2_SECTORS", bl["stage2_sectors"], False, ""),
            ("BOOT_KERNEL_SECTORS", bl["kernel_sectors"], False, "kernel load area"),
            ("BOOT_SPARE_SECTORS",  bl["spare_sectors"],  False, "boot+stage2+kernel+spare == fs_start"),
        ]))

    # Font metrics — the advance=8 fix lives here
    frows = [
        ("FONT_COUNT",           font["count"],   False, ""),
        ("FONT_DESC_SIZE",       6,               False, "bytes per font_table entry"),
        ("FONT_DEFAULT_INDEX",   font["default"], False, "8x8"),
    ]
    for ft in font["table"]:
        p = "FONT%d_" % ft["index"]
        frows += [(p+"WIDTH", ft["width"], False, ft["name"]),
                  (p+"HEIGHT", ft["height"], False, ""),
                  (p+"ADVANCE", ft["advance"], False, "the 12px bug is fixed in the Contract" if ft["index"]==font["default"] else ""),
                  (p+"BPC", ft["bpc"], False, "")]
    frows.append(("FONT_DEFAULT_ADVANCE",
                  next(f["advance"] for f in font["table"] if f["index"] == font["default"]),
                  False, "= 8 (NOT 12)"))
    G.append(("Font metrics", frows))

    # Screen / desktop
    G.append(("Screen & desktop metrics (x86 default mode)", [
        ("SCREEN_DEFAULT_MODE", scr["default_mode"], True,  "CGA mode 4"),
        ("SCREEN_WIDTH",        scr["width"],        False, ""),
        ("SCREEN_HEIGHT",       scr["height"],       False, ""),
        ("TITLEBAR_HEIGHT",     scr["titlebar_height"], False, "lo-res"),
        ("DESKTOP_RESERVED_ROWS", scr["desktop_reserved_rows"], False, "menu/title row"),
        ("ICON_COLUMN_PITCH",   scr["icon_column_pitch"], False, ""),
        ("CURSOR_W",            scr["cursor"]["w"],  False, ""),
        ("CURSOR_H",            scr["cursor"]["h"],  False, ""),
    ]))

    # UI palette (24-bit + 6-bit DAC channels)
    prows = []
    for i, rgb in enumerate(pal["rgb24"]):
        prows.append(("UI_PAL%d_RGB24" % i, rgb, True, pal["roles"][i]))
    for i, ch in enumerate(pal["vga6bit"]):
        prows += [("UI_PAL%d_R" % i, ch[0], False, ""),
                  ("UI_PAL%d_G" % i, ch[1], False, ""),
                  ("UI_PAL%d_B" % i, ch[2], False, "6-bit VGA DAC")]
    G.append(("UI palette (indices 0-3)", prows))

    # Enums
    for ename, evals in d["enum"].items():
        prefix = {"event_type":"EVENT_", "win_state":"WIN_STATE_",
                  "win_flags":"WIN_FLAG_", "fs_errno":"FS_ERR_"}.get(ename, ename.upper()+"_")
        rows = [(prefix + k, v, isinstance(v, int) and v >= 0x10, "")
                for k, v in evals.items()]
        G.append(("enum %s" % ename, rows))

    return G

def f_is_reserved(field_str):
    return field_str.strip().lower().startswith(("reserved", "_pad"))

# ---------------------------------------------------------------------------
# Renderers
# ---------------------------------------------------------------------------
def render_asm(d, dia, world):
    out = []
    for line in BANNER:
        out.append(dia.c(line))
    out.append(dia.c("world: %s" % world))
    out.append("")
    for heading, rows in build_rows(d):
        out.append(dia.c("-" * 4 + " " + heading + " " + "-" * max(2, 60 - len(heading))))
        for sym, val, hexfmt, comment in rows:
            line = dia.eq(sym, val, hexfmt)
            if comment:
                line = "%-44s %s %s" % (line, dia.comment, comment)
            out.append(line)
        out.append("")
    return "\n".join(out) + "\n"

def render_c(d):
    out = []
    out.append("/* " + BANNER[0] + " */")
    out.append("/* " + BANNER[1] + " */")
    out.append("#ifndef UNODEF_H")
    out.append("#define UNODEF_H")
    out.append("#include <stdint.h>")
    out.append("#include <stddef.h>")
    out.append("")
    # #defines (reuse the asm row model)
    for heading, rows in build_rows(d):
        if heading.startswith(("Window table", "Event record", "File handle",
                               "FAT12 directory", ".BIN app")):
            # offsets still useful as macros; structs emitted separately below
            pass
        out.append("/* ---- %s ---- */" % heading)
        for sym, val, hexfmt, comment in rows:
            v = ("0x%X" % val) if hexfmt else str(val)
            line = "#define %-28s %s" % (sym, v)
            if comment:
                line = "%-46s /* %s */" % (line, comment)
            out.append(line)
        out.append("")
    # Packed struct typedefs with static asserts (offsets ARE the contract)
    out.append("/* ---- struct layouts (byte-exact; verified by _Static_assert) ---- */")
    out.append("#if defined(__GNUC__) || defined(__clang__)")
    out.append("# define UNO_PACKED __attribute__((packed))")
    out.append("#else")
    out.append("# define UNO_PACKED")
    out.append("#endif")
    out.append("")
    for s in d["struct"]:
        out.append(render_c_struct(s))
        out.append("")
    # Const tables
    out.append(render_c_tables(d))
    out.append("#endif /* UNODEF_H */")
    return "\n".join(out) + "\n"

def render_c_struct(s):
    name = s["name"]
    fields = [parse_field(x) for x in s["fields"] if not f_is_reserved(x)]
    fields.sort(key=lambda f: f["off"])
    lines = ["typedef struct UNO_PACKED {"]
    cur = 0
    pad = 0
    asserts = []
    for f in fields:
        if f["off"] > cur:
            lines.append("    uint8_t _pad%d[%d];" % (pad, f["off"] - cur)); pad += 1
            cur = f["off"]
        base, arr = f["cty"]
        lines.append("    %s %s%s;" % (base, f["name"], arr))
        asserts.append("_Static_assert(offsetof(%s, %s) == %d, \"%s.%s\");"
                       % (name + "_t", f["name"], f["off"], name, f["name"]))
        cur += f["size"]
    if cur < s["size"]:
        lines.append("    uint8_t _pad%d[%d];" % (pad, s["size"] - cur))
    lines.append("} %s_t;" % name)
    lines.append("_Static_assert(sizeof(%s_t) == %d, \"%s size\");" % (name, s["size"], name))
    lines += asserts
    return "\n".join(lines)

def render_c_tables(d):
    font = d["const"]["font"]
    pal = d["const"]["palette"]
    out = ["/* ---- const tables ---- */"]
    out.append("typedef struct { uint8_t width, height, advance, bpc; } uno_font_desc_t;")
    out.append("static const uno_font_desc_t uno_font_table[%d] = {" % font["count"])
    for ft in font["table"]:
        out.append("    { %d, %d, %d, %d }, /* %d: %s */" %
                   (ft["width"], ft["height"], ft["advance"], ft["bpc"], ft["index"], ft["name"]))
    out.append("};")
    out.append("static const uint32_t uno_ui_palette_rgb24[4] = { %s };" %
               ", ".join("0x%06X" % c for c in pal["rgb24"]))
    out.append("static const uint8_t uno_ui_palette_vga6[4][3] = {")
    for ch in pal["vga6bit"]:
        out.append("    { %d, %d, %d }," % tuple(ch))
    out.append("};")
    return "\n".join(out) + "\n"

# ---------------------------------------------------------------------------
# Call-gate APP STUBS (CONTRACT-ARCH §3.2 row 1). Generated ONLY for worlds whose
# call binding is declared in [callgate.binding.*] — fabricating an unspecified ABI
# (6502/65816/Z80 have no binding yet) would defeat the single-source discipline.
# The stub sets the selector and invokes the gate; the caller sets the arg regs.
# ---------------------------------------------------------------------------
def render_stubs_x86(d):
    bnd = d["callgate"]["binding"]["x86"]
    out = ["; " + BANNER[0], "; " + BANNER[1],
           "; app-side call stubs — world: x86 / NASM",
           "; binding: %s, selector %s, %s" % (bnd["gate"], bnd["selector"], bnd["error"]),
           "; usage: set arg regs, then `sys_<name>` (sets AH + INT 0x80).", ""]
    for s in sorted(d["syscall"], key=lambda x: x["ordinal"]):
        out.append("%%macro sys_%s 0" % s["name"])
        out.append("    mov ah, %s" % sysname(s["name"]))
        out.append("    int 0x80")
        out.append("%endmacro")
    return "\n".join(out) + "\n"

def render_stubs_m68k(d):
    bnd = d["callgate"]["binding"]["m68k"]
    out = ["; " + BANNER[0], "; " + BANNER[1],
           "; app-side call stubs — world: 68000 / vasm",
           "; binding: %s, selector %s, %s" % (bnd["gate"], bnd["selector"], bnd["error"]),
           "; usage: set arg regs (D1-D4/A0-A1), then `sys_<name>` (D0.hi = ordinal, TRAP #0).", ""]
    for s in sorted(d["syscall"], key=lambda x: x["ordinal"]):
        out.append("sys_%s macro" % s["name"])
        out.append("    move.w  #(%s<<8),d0" % sysname(s["name"]))
        out.append("    trap    #0")
        out.append("    endm")
    return "\n".join(out) + "\n"

STUB_EMITTERS = {"x86": ("unosys.inc", render_stubs_x86),
                 "m68k": ("unosys.i", render_stubs_m68k)}

# ---------------------------------------------------------------------------
# World-neutral MANIFEST (CONTRACT-ARCH §3.2 last row: docs / conformance vectors).
# A machine-readable snapshot the conformance suite + doc regen consume — no dialect.
# ---------------------------------------------------------------------------
def render_manifest(d):
    import json
    m = {
        "contract": d["contract"]["abi_target"],
        "callgate": {"count": d["callgate"]["count"]},
        "syscalls": [{"ordinal": s["ordinal"], "name": s["name"], "category": s["category"]}
                     for s in sorted(d["syscall"], key=lambda x: x["ordinal"])],
        "structs":  {s["name"]: {"size": s["size"],
                                 "fields": [parse_field(x)["name"] + "@" + str(parse_field(x)["off"])
                                            for x in s["fields"]]}
                     for s in d["struct"]},
        "const": {"fat12": d["const"]["fat12"],
                  "font_default_advance": next(f["advance"] for f in d["const"]["font"]["table"]
                                               if f["index"] == d["const"]["font"]["default"])},
        "enums": d["enum"],
    }
    return json.dumps(m, indent=2) + "\n"

# ---------------------------------------------------------------------------
# Emit
# ---------------------------------------------------------------------------
WORLDS = [
    ("x86",   "unodef.inc", lambda d: render_asm(d, NASM, "x86 / NASM (kernel/)")),
    ("c",     "unodef.h",   render_c),
    ("m68k",  "unodef.i",   lambda d: render_asm(d, VASM, "68000 / vasm (amiga, genesis, macplus)")),
    ("6502",  "unodef.inc", lambda d: render_asm(d, DASM, "6502 / dasm (apple2, c64)")),
    ("65816", "unodef.inc", lambda d: render_asm(d, CA65, "65816 / ca65 (snes, iigs)")),
    ("z80",   "unodef.inc", lambda d: render_asm(d, Z80,  "Z80 / sjasmplus (sms, game boy)")),
]

# x86 trust-anchor: generated constants MUST equal kernel.asm's hand-written literals.
KERNEL_LITERALS = {
    "SYS_COUNT": 106,
    "WIN_ENTRY_SIZE": 32, "WIN_MAX_COUNT": 16, "WIN_OFF_OWNER": 11, "WIN_OFF_CONTENT_SCALE": 24,
    "FILE_ENTRY_SIZE": 32, "FILE_MAX_HANDLES": 16, "FILE_OFF_OWNER": 24,
    "EVENT_ENTRY_SIZE": 3, "EVENT_QUEUE_COUNT": 32,
    "FONT_COUNT": 3, "FONT_DESC_SIZE": 6, "FONT_DEFAULT_ADVANCE": 8,
    "FAT12_BYTES_PER_SECTOR": 512, "FAT12_RESERVED_SECTORS": 1, "FAT12_NUM_FATS": 2,
    "FAT12_ROOT_DIR_ENTRIES": 224, "FAT12_SECTORS_PER_FAT": 9, "FAT12_FS_START_SECTOR": 110,
    "FAT12_FAT_START": 111, "FAT12_ROOT_DIR_START": 129, "FAT12_DATA_AREA_START": 143,
}

def check(d):
    flat = {}
    for _, rows in build_rows(d):
        for sym, val, _h, _c in rows:
            flat[sym] = val
    bad = [(k, v, flat.get(k)) for k, v in KERNEL_LITERALS.items() if flat.get(k) != v]
    if bad:
        for k, want, got in bad:
            print("  FAIL %s: contract=%s  kernel.asm=%s" % (k, got, want))
        return False
    print("  trust anchor OK — %d generated x86 constants match kernel.asm literals" % len(KERNEL_LITERALS))
    return True

def _write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("emit %s" % os.path.relpath(path, ROOT).replace(os.sep, "/"))

def render_world_equates(d, world):
    """Per-port ABI variant (CONTRACT-ARCH §13): emit the port's OWN named equates
    from [world.<name>]. Phase 4 'describe what ships' — values are the port's, so
    generation is byte-identical to the hand-maintained block it replaces."""
    w = d["world"][world]
    dia = {"m68k": VASM}.get(w.get("cpu"), VASM)
    out = ["; " + BANNER[0], "; " + BANNER[1],
           "; world: %s — %s" % (world, w.get("description", "")), ""]
    if w.get("note"):
        out.append(dia.c(w["note"]))
    for e in w.get("equate", []):
        line = dia.eq(e["sym"], e["val"])
        if e.get("note"):
            line = "%-40s %s %s" % (line, dia.comment, e["note"])
        out.append(line)
    return "\n".join(out) + "\n"

def abi31_map(d):
    """Compute the 3.1 categorized ordinal for each syscall (CONTRACT-ARCH §11):
    new = band_base[category] + index-within-category. Collision-free by construction
    as long as no category exceeds band_width."""
    cfg = d["abi31"]; band = cfg["band_width"]; order = cfg["category_order"]
    base = {c: i * band for i, c in enumerate(order)}
    by_cat = {}
    out = {}
    for s in sorted(d["syscall"], key=lambda x: x["ordinal"]):
        c = s["category"]
        idx = by_cat.get(c, 0); by_cat[c] = idx + 1
        out[s["ordinal"]] = (base[c] + idx, c, s["name"], idx < band)
    return out, by_cat

def render_abi31(d):
    m, counts = abi31_map(d)
    out = ["UnoDOS 3.1 categorized ordinal map (generated; §11). flat -> 3.1.", ""]
    for flat in sorted(m):
        new, cat, name, ok = m[flat]
        out.append("  %3d  %-26s %-7s -> 0x%02X%s" % (flat, name, cat, new, "" if ok else "  !! BAND OVERFLOW"))
    out.append("")
    for c, n in counts.items():
        out.append("  category %-7s count=%d (band=%d)" % (c, n, d["abi31"]["band_width"]))
    return "\n".join(out) + "\n"

def render_profiles(d):
    """Per-port profile/capability/display manifest (CONTRACT-ARCH §9): what each
    port must provide. Makes 'this machine can't window' generated and honest."""
    prof = d.get("profile", {})
    out = ["UnoDOS port profile & capability manifest (generated by unogen).", ""]
    for name, p in d.get("port", {}).items():
        pf = p.get("profile", "?")
        req = prof.get(pf, {}).get("requires", [])
        caps = p.get("capabilities", [])
        surfs = p.get("surface", [])
        out.append("port %-12s profile=%-10s caps=[%s]" % (name, pf, ",".join(caps)))
        out.append("    requires: %s" % (", ".join(req) if req else "(none)"))
        if surfs:
            for s in surfs:
                out.append("    surface %-8s %dx%d role=%s" %
                           (s.get("id","?"), s.get("w",0), s.get("h",0), s.get("role","?")))
        else:
            out.append("    surfaces: (none — HEADLESS)" if "HEADLESS" in caps else "    surfaces: (unspecified)")
    return "\n".join(out) + "\n"

def main():
    d = load()
    bound = set(d["callgate"]["binding"].keys())
    for world, fname, render in WORLDS:
        _write(os.path.join(GEN, world, fname), render(d))
        # Call-gate app stubs — only where a binding is declared in the Contract.
        if world in STUB_EMITTERS:
            sf, sr = STUB_EMITTERS[world]
            _write(os.path.join(GEN, world, sf), sr(d))
        elif world not in ("c",):
            print("  note: %-6s has no [callgate.binding.%s] — app stubs skipped "
                  "(declare its call ABI in the Contract to generate them)" % (world, world))
    _write(os.path.join(GEN, "manifest.json"), render_manifest(d))
    # Per-world ABI variants (Phase 4): emit each [world.<name>]'s own equates.
    for wname, w in d.get("world", {}).items():
        emit = w.get("emit", wname + "/sysabi_gen.i")
        base = os.path.basename(emit)
        _write(os.path.join(GEN, wname, base), render_world_equates(d, wname))
    _write(os.path.join(GEN, "profiles.txt"), render_profiles(d))
    _write(os.path.join(GEN, "abi31_ordinals.txt"), render_abi31(d))
    if "--check" in sys.argv:
        print("checking x86 trust anchor...")
        if not check(d):
            sys.exit(1)

if __name__ == "__main__":
    main()
