#!/usr/bin/env python3
"""wmgen — GREENFIELD prototype generator (CONTRACT-ARCH §11 redux).

Where unogen emits FIXED @offset equates, wmgen carries NO offsets in the
Contract. It reads the LOGICAL [wmodel] from unodef/unodef.toml and DERIVES a
per-PLATFORM physical representation (column widths from the field kind + the
platform's coord space, SoA storage, capacity) + zero-cost ACCESSORS, so
portable policy touches window data only through win_get_*/win_set_* keyed by an
integer handle — never a raw offset. This is the tall-vtable pattern applied to
DATA: one logical model, an optimal per-platform realization behind one boundary.

Floor = SoA (columnar). Each field is its own array indexed by the handle, which
gives FREE indexing on every CPU (the handle IS the index — no stride multiply,
unlike a 16-byte AoS entry that needs `<<4` on a 6502) and contiguous columns
that a big machine can composite with SIMD. AoS would be a per-platform override
behind the same accessors; not needed for the floor.

Usage: python unodef/wmgen.py        # emit unodef/gen/wm/<platform>/...
"""
import os, tomllib

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DEF  = os.path.join(HERE, "unodef.toml")
GEN  = os.path.join(HERE, "gen", "wm")

BANNER = ("GENERATED by unodef/wmgen.py from unodef/unodef.toml [wmodel] — DO NOT EDIT.\n"
          "Physical layout DERIVED from the logical model + this platform descriptor.")

CTYPE = {1: "uint8_t", 2: "uint16_t", 4: "uint32_t", 8: "uint64_t"}


def load():
    with open(DEF, "rb") as f:
        return tomllib.load(f)


def col_width(field, plat):
    """Derive a field's column width (bytes) from its KIND + the platform."""
    k = field["kind"]
    if k == "coord":
        m = plat["coord_max"]
        return 1 if m < 256 else (2 if m < 65536 else 4)
    if k in ("enum", "task", "bitset8"):
        return 1
    if k == "strhandle":
        return plat["ptr_bits"] // 8
    raise ValueError("unknown kind %r" % k)


def layout(model, plat):
    """Compute the derived SoA layout: ordered columns (hot first), widths, the
    z-order relation column, total bytes. Pure function of the logical model +
    descriptor — the whole point: no offsets live in the Contract."""
    fields = model["window"]["field"]
    cap = plat["capacity"]
    ordered = [f for f in fields if f.get("tier") == "hot"] + \
              [f for f in fields if f.get("tier") != "hot"]
    cols, base = [], int(plat.get("storage", 0))
    for f in ordered:
        w = col_width(f, plat)
        cols.append(dict(name=f["name"], kind=f["kind"], tier=f.get("tier", "hot"),
                         width=w, base=base, bytes=w * cap))
        base += w * cap
    # z-order relation: a separate ordered list of handles (top..bottom).
    zcol = dict(name="z_list", kind="relation", tier="hot",
                width=1, base=base, bytes=cap)   # handle index fits in 1 byte for these caps
    base += cap
    total = base - int(plat.get("storage", 0))
    return ordered, cols, zcol, total


def c_policy(plat):
    """The portable L2 window policy — WRITE-ONCE, touches data ONLY through the
    generated accessors, so it is identical source on every C-capable platform
    (host/amd64/x86/arm64/…). This is the payoff of full field access."""
    cc = CTYPE[col_width({'kind': 'coord'}, plat)]
    return [
        "/* --- portable L2 policy: WRITE-ONCE, via accessors only (full field access). */",
        "static inline int win_hit(int i, %s px, %s py){" % (cc, cc),
        "    return px >= win_get_x(i) && px < win_get_x(i) + win_get_w(i)",
        "        && py >= win_get_y(i) && py < win_get_y(i) + win_get_h(i);",
        "}",
        "static inline void win_move  (int i, %s nx, %s ny){ win_set_x(i,nx); win_set_y(i,ny); }" % (cc, cc),
        "static inline void win_resize(int i, %s nw, %s nh){ win_set_w(i,nw); win_set_h(i,nh); }" % (cc, cc),
        "static inline void win_reap(uint8_t dead){",
        "    for (int i=0;i<WIN_CAP;i++) if (win_get_state(i) && win_get_owner(i)==dead) win_set_state(i,0);",
        "}",
        "/* z-order raise: promote handle to rank 0 (top), shifting the rest down. */",
        "static inline void win_raise(int handle, int nlive){",
        "    int r; for (r=0;r<nlive;r++) if (win_z_at(r)==handle) break;",
        "    for (; r>0; r--) win_z_set(r, win_z_at(r-1));",
        "    win_z_set(0, (uint8_t)handle);",
        "}",
        "/* topmost live window containing (px,py): walk the z-list top->bottom. */",
        "static inline int win_topmost_at(int nlive, %s px, %s py){" % (cc, cc),
        "    for (int r=0;r<nlive;r++){ int h=win_z_at(r); if (win_get_state(h) && win_hit(h,px,py)) return h; }",
        "    return -1;",
        "}", ""]


def layout_aos(model, plat):
    """AoS variant: pack all fields into ONE entry with natural alignment; the
    table is capacity entries. Proves 'fixed-offset' is just a layout strategy —
    same logical model, different physical shape. (Hot fields first, then cold.)"""
    fields = model["window"]["field"]
    ordered = [f for f in fields if f.get("tier") == "hot"] + \
              [f for f in fields if f.get("tier") != "hot"]
    # alignment is per-platform: x86/C aligns to the field width; 68000 only needs
    # WORD (2-byte) alignment even for longs, so max_align caps it.
    cap_align = plat.get("max_align", 8)
    off, ents = 0, []
    for f in ordered:
        w = col_width(f, plat)
        a = min(w, cap_align)
        if a > 1 and off % a:
            off += a - (off % a)
        ents.append(dict(name=f["name"], kind=f["kind"], tier=f.get("tier", "hot"),
                         width=w, off=off))
        off += w
    ealign = min(max(e["width"] for e in ents), cap_align)
    if off % ealign:
        off += ealign - (off % ealign)           # pad entry to its alignment
    if plat.get("pad_pow2"):                      # power-of-two stride for shift-indexing
        p = 1
        while p < off:
            p <<= 1
        off = p
    return ordered, ents, off                    # off == entry_size


# ---------------------------------------------------------------------------
# C world, AoS layout: one struct + a table. Same accessors, same write-once
# policy — only the physical shape differs from SoA. A _Static_assert checks the
# generator's offset math against the compiler's struct layout.
# ---------------------------------------------------------------------------
def emit_c_aos(model, name, plat):
    ordered, ents, esz = layout_aos(model, plat)
    cap = plat["capacity"]
    L = ["/* %s */" % BANNER.replace("\n", "\n   "),
         "/* platform: %s — %s, %d-bit, %s coords (max %d), capacity %d, layout=AOS */"
         % (name, plat["cpu"], plat["word_bits"], plat["coord_space"],
            plat["coord_max"], cap),
         "#pragma once", "#include <stdint.h>", "",
         "#define WIN_CAP        %d" % cap,
         "#define WIN_ENTRY_SIZE %d" % esz, "",
         "typedef struct {"]
    for e in ents:
        L.append("    %-9s %-12s;  /* @%-2d %s */" % (CTYPE[e["width"]], e["name"], e["off"], e["tier"]))
    L += ["} win_entry_t;",
          "_Static_assert(sizeof(win_entry_t) == WIN_ENTRY_SIZE, \"AoS offset math == compiler layout\");",
          "extern win_entry_t wtab[WIN_CAP];",
          "extern uint8_t     wz_list[WIN_CAP];   /* z-order relation (top..bottom) */", "",
          "/* --- accessors: same names as the SoA world; here they index the struct --- */"]
    for e in ents:
        cty, g = CTYPE[e["width"]], e["name"]
        L.append("static inline %-9s win_get_%-11s(int i){ return wtab[i].%s; }" % (cty, g, g))
        L.append("static inline void      win_set_%-11s(int i, %-9s v){ wtab[i].%s=v; }" % (g, cty, g))
    L += ["static inline uint8_t win_z_at(int rank){ return wz_list[rank]; }",
          "static inline void    win_z_set(int rank, uint8_t handle){ wz_list[rank]=handle; }",
          "", "/* --- the SAME write-once policy as the SoA world (layout-independent) --- */"]
    L += c_policy(plat)
    emit_c_aos.storage = ('/* %s */\n#include "window.h"\n\n'
                          "win_entry_t wtab[WIN_CAP];\nuint8_t wz_list[WIN_CAP];\n"
                          % BANNER.replace("\n", "\n   "))
    return "\n".join(L), ents, esz


# ---------------------------------------------------------------------------
# 68000 / vasm world (16/32-bit): SoA column bases + get/set MACROS. 68000 has NO
# scaled index addressing, so u16 columns double the handle first — a per-platform
# accessor difference the generator handles, invisible to portable policy.
# ---------------------------------------------------------------------------
def emit_vasm(model, name, plat):
    if plat.get("layout") == "aos":
        return emit_vasm_aos(model, name, plat)
    ordered, cols, zcol, total = layout(model, plat)
    cap = plat["capacity"]
    L = ["; " + BANNER.replace("\n", "\n; "),
         "; platform: %s — %s, %d-bit, %s coords (max %d), capacity %d, layout=%s"
         % (name, plat["cpu"], plat["word_bits"], plat["coord_space"],
            plat["coord_max"], cap, plat["layout"]),
         "%-22s equ %d" % ("WIN_CAP", cap), "",
         "; --- storage: struct-of-arrays (column bases) ---"]
    for c in cols:
        note = "[%d]u%d%s" % (cap, c["width"] * 8, "  ; cold" if c["tier"] != "hot" else "")
        L.append("%-22s equ $%05X     ; %s" % ("wc_" + c["name"], c["base"], note))
    L.append("%-22s equ $%05X     ; z-order relation, top..bottom" % ("wz_list", zcol["base"]))
    L += ["", "; --- accessors (macros): d0.w = handle; result/value in d1; a0 = scratch ---",
          "; 68000 has no scaled index, so u16 columns double the handle first.", ""]
    for c in cols:
        g, w = c["name"], c["width"]
        if w == 1:
            L += ["win_get_%s macro" % g,
                  "            lea wc_%s,a0" % g,
                  "            move.b (a0,d0.w),d1",
                  "            endm",
                  "win_set_%s macro     ; d1.b = value" % g,
                  "            lea wc_%s,a0" % g,
                  "            move.b d1,(a0,d0.w)",
                  "            endm"]
        elif w == 2:
            L += ["win_get_%s macro" % g,
                  "            lea wc_%s,a0" % g,
                  "            move.w d0,d1",
                  "            add.w d1,d1        ; *2 (no scaled index on 68000)",
                  "            move.w (a0,d1.w),d1",
                  "            endm",
                  "win_set_%s macro     ; d2.w = value" % g,
                  "            lea wc_%s,a0" % g,
                  "            move.w d0,d1",
                  "            add.w d1,d1",
                  "            move.w d2,(a0,d1.w)",
                  "            endm"]
    L += ["win_z_at macro       ; d0.w = rank -> d1.b = handle",
          "            lea wz_list,a0",
          "            move.b (a0,d0.w),d1",
          "            endm", ""]
    return "\n".join(L), cols, zcol, total


# ---------------------------------------------------------------------------
# 65816 / ca65 world, AoS layout: emit WIN_ENTRY_SIZE + a win_index_to_x macro
# (window slot index -> X = byte offset, via `shift` x `asl a` + `tax`). The
# 65816 ports index the AoS table by a byte offset in X; this single-sources the
# stride the kernel hand-wrote at ent_x / zent_x. Used to wire SNES + IIGS.
# ---------------------------------------------------------------------------
def emit_ca65_aos(model, name, plat):
    ordered, ents, esz = layout_aos(model, plat)
    shift = (esz.bit_length() - 1) if (esz & (esz - 1)) == 0 else None
    if shift is None:
        raise ValueError("entry size %d is not a power of two — no shift form" % esz)
    L = ["; " + BANNER.replace("\n", "\n; "),
         "; platform: %s — %s, %d-bit, %s coords (max %d), capacity %d, layout=AOS"
         % (name, plat["cpu"], plat["word_bits"], plat["coord_space"],
            plat["coord_max"], plat["capacity"]),
         "%-22s = %d" % ("WIN_CAP", plat["capacity"]),
         "%-22s = %d" % ("WIN_ENTRY_SIZE", esz), "",
         "; field offsets DERIVED from the logical model (match the port's [world.%s]):" % name]
    for e in ents:
        L.append(";   %-12s @%-2d u%-2d %s" % (e["name"], e["off"], e["width"] * 8, e["tier"]))
    L += ["",
          "; win_index_to_x: A = window slot index -> X = byte offset (index * %d)." % esz,
          "; Single-sources the stride (%d x asl) the kernel hand-wrote at ent_x/zent_x." % shift,
          ".macro win_index_to_x"]
    L += ["    asl a"] * shift
    L += ["    tax", ".endmacro"]
    # full field access: offsets + lda/sta convenience macros (X = entry byte offset).
    base = plat.get("entry_base", "v_wintab")
    L += ["", "; --- full field access: offsets + lda/sta macros (X = entry byte offset) ---"]
    for e in ents:
        L.append("%-22s = %d" % ("WIN_" + e["name"].upper(), e["off"]))
    for e in ents:
        nm = e["name"]
        L += [".macro win_lda_%s" % nm, "    lda %s+WIN_%s,x" % (base, nm.upper()), ".endmacro",
              ".macro win_sta_%s" % nm, "    sta %s+WIN_%s,x" % (base, nm.upper()), ".endmacro"]
    return "\n".join(L) + "\n", ents, None, esz * plat["capacity"]


# ---------------------------------------------------------------------------
# x86 / NASM world, AoS layout: emit a win_entry_addr macro (handle reg -> entry
# address) single-sourcing the stride + base the kernel hand-wrote. Uses an
# explicit entry_size override (the shipping x86 win_entry is 32B). The kernel's
# field offsets keep coming from the Contract's [struct] win_entry; this wires the
# index->address arithmetic, matching the other 5 ports. NASM %macro takes the
# handle register as its argument.
# ---------------------------------------------------------------------------
def emit_nasm_aos(model, name, plat):
    ents, esz = layout_aos(model, plat)[1], plat.get("entry_size", layout_aos(model, plat)[2])
    shift = (esz.bit_length() - 1) if (esz & (esz - 1)) == 0 else None
    if shift is None:
        raise ValueError("entry size %d is not a power of two" % esz)
    base = plat.get("entry_base", "window_table")
    shmac = plat.get("shift_macro", "SHL_N")
    L = ["; " + BANNER.replace("\n", "\n; "),
         "; platform: %s — %s, %d-bit, %s coords (max %d), capacity %d, layout=AOS, entry=%dB"
         % (name, plat["cpu"], plat["word_bits"], plat["coord_space"],
            plat["coord_max"], plat["capacity"], esz), "",
         "; win_entry_addr <reg>: reg = window handle -> reg = entry address.",
         "; Single-sources the stride (%s <reg>,%d = *%d) + base (%s) the kernel hand-wrote."
         % (shmac, shift, esz, base),
         "%macro win_entry_addr 1",
         "    %s %%1, %d" % (shmac, shift),
         "    add %%1, %s" % base,
         "%endmacro"]
    return "\n".join(L) + "\n", ents, None, esz * plat["capacity"]


# ---------------------------------------------------------------------------
# 68000 / vasm world, AoS layout: emit WIN_ENTRY_SIZE + a win_entry_ptr macro
# (slot index -> entry pointer) that single-sources the index->address arithmetic
# a 68000 port hand-writes. Used to wire a REAL shipped port byte-identically.
# ---------------------------------------------------------------------------
def emit_vasm_aos(model, name, plat):
    ordered, ents, esz = layout_aos(model, plat)
    shift = (esz.bit_length() - 1) if (esz & (esz - 1)) == 0 else None
    base = plat.get("entry_base", "wintab")
    pcrel = "(pc)" if plat.get("pc_relative") else ""
    L = ["; " + BANNER.replace("\n", "\n; "),
         "; platform: %s — %s, %d-bit, %s coords (max %d), capacity %d, layout=AOS"
         % (name, plat["cpu"], plat["word_bits"], plat["coord_space"],
            plat["coord_max"], plat["capacity"]),
         "%-22s equ %d" % ("WIN_CAP", plat["capacity"]),
         "%-22s equ %d" % ("WIN_ENTRY_SIZE", esz), "",
         "; field offsets DERIVED from the logical model (match the port's [world.%s]):" % name]
    for e in ents:
        L.append(";   %-12s @%-2d u%-2d %s" % (e["name"], e["off"], e["width"] * 8, e["tier"]))
    if shift is None:
        raise ValueError("entry size %d is not a power of two — no shift form" % esz)
    L += ["",
          "; win_entry_ptr: d2.w = slot index -> a2 = entry pointer (AoS, stride %d)." % esz,
          "; Single-sources the stride (lsl #%d) + base (%s%s) the kernel hand-wrote" % (shift, base, pcrel),
          "; at win_ptr_raw / zwin_ptr.  Expands to the SAME instructions -> byte-identical.",
          "win_entry_ptr macro",
          "            lsl.w #%d,d2" % shift,
          "            lea %s%s,a2" % (base, pcrel),
          "            lea (a2,d2.w),a2",
          "            endm"]
    # full field access: offsets + get/set convenience macros (entry ptr in an An).
    sfx = {1: "b", 2: "w", 4: "l"}
    L += ["", "; --- full field access: offsets + get/set macros (\\1 = entry An, \\2 = data Dn) ---"]
    for e in ents:
        L.append("%-22s equ %d" % ("WIN_" + e["name"].upper(), e["off"]))
    for e in ents:
        nm, s = e["name"], sfx[e["width"]]
        L += ["win_ld_%s macro" % nm, "            move.%s WIN_%s(\\1),\\2" % (s, nm.upper()), "            endm",
              "win_st_%s macro" % nm, "            move.%s \\2,WIN_%s(\\1)" % (s, nm.upper()), "            endm"]
    return "\n".join(L) + "\n", ents, None, esz * plat["capacity"]


# ---------------------------------------------------------------------------
# C world (32/64-bit): SoA columns + static-inline accessors + the SAME portable
# L2 policy snippet, written ONCE against the accessors.
# ---------------------------------------------------------------------------
def emit_c(model, name, plat):
    ordered, cols, zcol, total = layout(model, plat)
    cap = plat["capacity"]
    L = ["/* %s */" % BANNER.replace("\n", "\n   "),
         "/* platform: %s — %s, %d-bit, %s coords (max %d), capacity %d, layout=%s */"
         % (name, plat["cpu"], plat["word_bits"], plat["coord_space"],
            plat["coord_max"], cap, plat["layout"]),
         "#pragma once", "#include <stdint.h>", "",
         "#define WIN_CAP %d" % cap, "",
         "/* --- storage: struct-of-arrays, one column per field, index = handle.",
         "       Declared extern here; defined once in window_storage.c so a port",
         "       can place hot/cold columns in the RAM it wants. --- */"]
    def cty_of(c):
        return CTYPE[c["width"]]   # strhandle width = ptr_bits/8 (a fixed-width handle)
    for c in cols:
        tag = "" if c["tier"] == "hot" else "  /* cold: may live in slower RAM */"
        L.append("extern %-9s wc_%-12s[WIN_CAP];%s" % (cty_of(c), c["name"], tag))
    L.append("extern uint8_t   wz_list      [WIN_CAP];  /* z-order relation (top..bottom) */")
    # storage definitions (one .c) — the columns the header declares extern.
    S = ["/* %s */" % BANNER.replace("\n", "\n   "),
         '#include "window.h"', ""]
    for c in cols:
        S.append("%-9s wc_%-12s[WIN_CAP];" % (cty_of(c), c["name"]))
    S.append("uint8_t   wz_list      [WIN_CAP];")
    emit_c.storage = "\n".join(S) + "\n"

    L += ["", "/* --- zero-cost accessors (the boundary) — compile to a single load/store --- */"]
    for c in cols:
        cty = cty_of(c)
        g = c["name"]
        L.append("static inline %-9s win_get_%-11s(int i){ return wc_%s[i]; }" % (cty, g, g))
        L.append("static inline void      win_set_%-11s(int i, %-9s v){ wc_%s[i]=v; }" % (g, cty, g))
    L += ["", "/* z-order relation accessors */",
          "static inline uint8_t win_z_at(int rank){ return wz_list[rank]; }",
          "static inline void    win_z_set(int rank, uint8_t handle){ wz_list[rank]=handle; }",
          ""]
    L += c_policy(plat)
    return "\n".join(L), cols, zcol, total


# ---------------------------------------------------------------------------
# 6502 / dasm world (8-bit): SoA column bases + get/set MACROS. The handle in Y
# indexes every column directly — NO stride multiply (the SoA payoff on 8-bit).
# ---------------------------------------------------------------------------
def emit_dasm(model, name, plat):
    ordered, cols, zcol, total = layout(model, plat)
    cap = plat["capacity"]
    L = ["; " + BANNER.replace("\n", "\n; "),
         "; platform: %s — %s, %d-bit, %s coords (max %d), capacity %d, layout=%s"
         % (name, plat["cpu"], plat["word_bits"], plat["coord_space"],
            plat["coord_max"], cap, plat["layout"]),
         "%-22s EQU %d" % ("WIN_CAP", cap), "",
         "; --- storage: struct-of-arrays; index = handle in Y, no stride multiply ---"]
    for c in cols:
        note = "[%d]u%d" % (cap, c["width"] * 8) + ("  ; cold" if c["tier"] != "hot" else "")
        if c["kind"] == "strhandle" and c["width"] == 2:
            # a 16-bit handle becomes lo/hi columns (still index-only on 6502)
            L.append("%-22s EQU $%04X       ; %s lo" % ("wc_%s_lo" % c["name"], c["base"], note))
            L.append("%-22s EQU $%04X       ; %s hi" % ("wc_%s_hi" % c["name"], c["base"] + cap, note))
        else:
            L.append("%-22s EQU $%04X       ; %s" % ("wc_%s" % c["name"], c["base"], note))
    L.append("%-22s EQU $%04X       ; z-order relation, top..bottom" % ("wz_list", zcol["base"]))
    L += ["", "; --- accessors (macros): Y = window handle ------------------------------",
          "; u8 fields: A = value.  Single indexed load/store — the SoA win on 6502",
          "; (vs the legacy 16-byte AoS entry, which needed txa/asl x4 to index).",
          ""]
    for c in cols:
        if c["width"] != 1:
            continue  # u8 columns get the simple register macros in this floor demo
        g = c["name"]
        L += ["            MAC win_get_%s   ; -> A" % g,
              "            lda wc_%s,y" % g,
              "            ENDM",
              "            MAC win_set_%s   ; A ->" % g,
              "            sta wc_%s,y" % g,
              "            ENDM"]
    L += ["            MAC win_z_at     ; rank in Y -> A = handle",
          "            lda wz_list,y",
          "            ENDM", ""]
    return "\n".join(L), cols, zcol, total


def main():
    d = load()
    model = d["wmodel"]
    plats = model["platform"]
    print("wmgen — deriving per-platform window layouts from the logical model\n")
    summary = []

    def write(name, fn, text):
        out = os.path.join(GEN, name, fn)
        os.makedirs(os.path.dirname(out), exist_ok=True)
        with open(out, "w", newline="\n") as f:
            f.write(text + "\n")
        print("  emit %s" % os.path.relpath(out, ROOT).replace("\\", "/"))

    for name, plat in plats.items():
        dialect, lay = plat["dialect"], plat.get("layout", "soa")
        spec = plat.get("spec_only", False)
        # Compute the derived layout numbers for EVERY platform (the spec table);
        # emit dialect files only for non-spec platforms (avoids redundant near-
        # identical C headers for the architecture survey).
        if lay == "aos":
            cols, total = layout_aos(model, plat)[1], layout_aos(model, plat)[2] * plat["capacity"]
        else:
            cols, total = layout(model, plat)[1], layout(model, plat)[3]
        if not spec:
            if dialect == "c" and lay == "aos":
                text, _, esz = emit_c_aos(model, name, plat)
                write(name, "window.h", text); write(name, "window_storage.c", emit_c_aos.storage)
            elif dialect == "c":
                text = emit_c(model, name, plat)[0]
                write(name, "window.h", text); write(name, "window_storage.c", emit_c.storage)
            elif dialect == "dasm":
                write(name, "window.inc", emit_dasm(model, name, plat)[0])
            elif dialect == "vasm":
                write(name, "window.i", emit_vasm(model, name, plat)[0])
            elif dialect == "ca65":
                write(name, "window.inc", emit_ca65_aos(model, name, plat)[0])
            elif dialect == "nasm":
                write(name, "window.inc", emit_nasm_aos(model, name, plat)[0])
            else:
                print("  skip %s (dialect %s not in this prototype)" % (name, dialect)); continue
        summary.append((name, plat.get("cpu", "?"), lay, dialect, plat.get("word_bits", 0),
                        plat.get("ptr_bits", 0), plat.get("endian", "le"),
                        plat["coord_space"], plat["capacity"], total, spec))

    # Consolidated architecture spec — one artifact for the whole survey.
    hdr = "%-9s %-8s %-3s %-6s %3s %3s %3s %-6s %4s %6s  %s" % (
        "platform", "cpu", "lay", "dialect", "wrd", "ptr", "end", "coords", "cap", "table", "")
    lines = [hdr, "-" * len(hdr)]
    for n, cpu, lay, dia, wb, pb, en, cs, cap, total, spec in summary:
        lines.append("%-9s %-8s %-3s %-6s %3d %3d %3s %-6s %4d %5dB  %s" %
                     (n, cpu, lay, dia, wb, pb, en, cs, cap, total, "(spec)" if spec else "wired/built"))
    write("", "ARCHITECTURES.txt", "UnoDOS window model — per-architecture derived layouts (one logical model).\n\n"
          + "\n".join(lines) + "\n")
    print("\n" + "\n".join(lines))


if __name__ == "__main__":
    main()
