#!/usr/bin/env python3
"""Compute the on-disk layout of the disk-loaded apps and emit:
  - build/app_layout.inc : the kernel's app_track[]/app_secs[] tables (per app
    id: start track + sector count), included by kernel.s.
  - build/app_placement.txt : one "id track sectors binpath" line per app, for
    mkdsk.py to copy the binaries onto the image.

Each app is track-aligned (starts at sector 0 of its track) so the kernel
loader can read it as "N sectors from (start track, logical sector 0),
spilling into the next track every 16 sectors". App ids are icon indices:
0=SysInfo,1=Clock have no binary; 2..9 are disk apps.

Usage: applayout.py <kernel.bin> <out_dir>
  expects <out_dir>/<app>.bin to already exist for each placed app.
"""
import sys
import os

TRACK = 4096
SECTOR = 256
SPT = 16                 # logical sectors per track
TRACKS = 35
FS_TRACK = 20            # apps must stay below the mini-FS region

# app id -> binary base name (matches build/<name>.bin). 0/1 have no binary.
APPS = [
    (2, "files_notepad"),
    (3, "theme"),
    (4, "dostris"),
    (5, "pacman"),
    (6, "music"),
    (7, "tracker"),
    (8, "paint"),
    (9, "outlast"),
]
NICONS = 10


def main():
    kern_p, outdir = sys.argv[1], sys.argv[2]
    ksize = os.path.getsize(kern_p)
    ktracks = (ksize + TRACK - 1) // TRACK
    next_track = 1 + ktracks            # first free track after the kernel

    track = [0] * NICONS
    secs = [0] * NICONS
    placement = []
    for app_id, name in APPS:
        binp = os.path.join(outdir, name + ".bin")
        size = os.path.getsize(binp)
        nsec = (size + SECTOR - 1) // SECTOR
        ntrk = (nsec + SPT - 1) // SPT
        assert next_track + ntrk <= FS_TRACK, (
            "app region overflow: %s at track %d needs %d track(s), FS at %d"
            % (name, next_track, ntrk, FS_TRACK))
        track[app_id] = next_track
        secs[app_id] = nsec
        placement.append((app_id, next_track, nsec, binp))
        next_track += ntrk

    with open(os.path.join(outdir, "app_layout.inc"), "w") as f:
        f.write("; generated by applayout.py - per-app-id (track, sector-count)\n")
        f.write("app_track: dc.b %s\n" % ",".join(str(t) for t in track))
        f.write("app_secs:  dc.b %s\n" % ",".join(str(s) for s in secs))

    with open(os.path.join(outdir, "app_placement.txt"), "w") as f:
        for app_id, t, n, binp in placement:
            f.write("%d %d %d %s\n" % (app_id, t, n, binp))

    print("app layout (kernel %dB = %d track(s); apps tracks %d..%d):"
          % (ksize, ktracks, 1 + ktracks, next_track - 1))
    for app_id, t, n, binp in placement:
        print("  id %d %-14s track %2d  %2d sector(s)  (%dB)"
              % (app_id, os.path.basename(binp), t, n, os.path.getsize(binp)))


if __name__ == "__main__":
    main()
