#!/bin/sh
# UnoDOS/AppleII build: boot0+RWTS + slim kernel + disk-loaded apps -> bootable
# 140K .dsk image. The apps (theme/dostris/pacman/.../files_notepad) are NOT
# compiled into the kernel; they are separate binaries on the disk, loaded at
# runtime into APP_BASE via RWTS and linked to the kernel by the addresses in
# build/kernel_api.inc (generated by mkapi.py).
#
# Requires dasm (6502 cross-assembler) and python3 (py65 for harness.py).
# Usage: ./build.sh [test]    ("test" auto-opens SysInfo + Clock at boot)
set -e
cd "$(dirname "$0")"

PY="${PY:-python3}"
DASM="${DASM:-/c/Users/arin/apple2-tools/dasm.exe}"

mkdir -p build
echo "[1/9] generating shared data (font/icons) from x86 tree assets..."
(cd .. && "$PY" amiga/mkdata.py amiga/gen_data.i)

echo "[2/9] converting the shared font + note tables..."
"$PY" mkfont.py
"$PY" mknotes.py

case "$1" in
  test)
    DEF="-DAUTOTEST=1"; DSK=build/unodos_apple2_test.dsk ;;
  sched)
    DEF="-DSCHED_PROTO=1"; DSK=build/unodos_sched.dsk ;;   # scheduler proto
  *)
    DEF=""; DSK=build/unodos_apple2.dsk ;;
esac

echo "[3/9] assembling boot.s..."
"$DASM" boot.s -f3 -obuild/boot.bin -lbuild/boot.lst

echo "[4/9] assembling kernel.s (pass 1: size probe, placeholder app layout)..."
# a placeholder all-zero app_layout.inc keeps pass-1 resolvable; the table size
# is fixed (NICONS bytes x2) so the kernel size is identical in pass 2.
printf 'app_track: dc.b 0,0,0,0,0,0,0,0,0,0\napp_secs:  dc.b 0,0,0,0,0,0,0,0,0,0\n' > build/app_layout.inc
"$DASM" kernel.s -f3 $DEF -obuild/kernel.bin -lbuild/kernel.lst -sbuild/kernel.sym

echo "[5/9] exporting the kernel API for disk-loaded apps..."
"$PY" mkapi.py build/kernel.sym build/kernel_api.inc

echo "[6/9] generating + assembling disk-loaded apps (org \$6000)..."
"$PY" mkapps.py
for app in theme dostris pacman music tracker paint outlast files_notepad; do
  "$DASM" build/$app.s -f3 $DEF -obuild/$app.bin -lbuild/$app.lst
done

echo "[7/9] computing app disk layout + re-assembling kernel (pass 2)..."
"$PY" applayout.py build/kernel.bin build
"$DASM" kernel.s -f3 $DEF -obuild/kernel.bin -lbuild/kernel.lst -sbuild/kernel.sym
# pass-2 kernel must match the API addresses apps were linked against
"$PY" mkapi.py build/kernel.sym build/kernel_api.inc.chk
if ! cmp -s build/kernel_api.inc build/kernel_api.inc.chk; then
  echo "ERROR: kernel API addresses shifted between passes - apps are stale!" >&2
  diff build/kernel_api.inc build/kernel_api.inc.chk >&2 || true
  exit 1
fi
rm -f build/kernel_api.inc.chk

echo "[8/9] packing the 35-track DOS-order disk image + apps..."
"$PY" mkdsk.py build/boot.bin build/kernel.bin "$DSK" build/app_placement.txt
"$PY" mkfs.py "$DSK"

echo "[9/9] emitting .woz + .nib for real hardware (FloppyEmu, IIc)..."
"$PY" mkwoz.py "$DSK" "${DSK%.dsk}"
echo "done: $DSK (+ .woz/.nib)"
