#!/usr/bin/env python3
"""Generate the standalone disk-app source files (build/<app>.s) from the
historical inline app bodies (<app>.i). Each emitted .s is a raw binary
assembled at APP_BASE with the disk-app ABI header (3-entry JMP table to
init/key/tick), includes sys.inc + the generated kernel_api.inc (so it links
to the kernel by address), carries the app's OWN state variables (moved out of
the kernel vars block) and its OWN message strings, and replaces the old
<app>_open / <app>_close lifecycle with the ABI: init does the open-time setup
+ first draw, and ESC jumps to return_to_desktop.

This is the Apple II analogue of the C64 hand-written pacman.s/tracker.s etc.;
generating them keeps the (large, well-tested) app bodies verbatim and only
rewrites the thin lifecycle shell. Files+Notepad combine into one binary
(files_notepad.s, see below).

Usage: mkapps.py        (run from apple2/, after the kernel .i bodies exist)
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "build")

# Per-app variable declarations moved out of the kernel vars block. These are
# appended (as a labelled dc.b/dc.w block) to each app binary so the app owns
# its own state. Verbatim from the old kernel.s vars section.
VARS = {
    "theme": """\
th_sel:      dc.b 0       ; Theme: highlighted preset (cursor)
th_cur:      dc.b 0       ; Theme: currently-applied preset (matches pat_tab)
""",
    "dostris": """\
dos_piece:   dc.b 0
dos_rot:     dc.b 0
dos_px:      dc.b 0
dos_py:      dc.b 0
dos_next:    dc.b 0
dos_score:   dc.w 0
dos_lines:   dc.b 0
dos_level:   dc.b 0
dos_dctr:    dc.b 0
dos_paused:  dc.b 0
dos_over:    dc.b 0
dos_rng:     dc.b 1
dos_justlock: dc.b 0
""",
    "pacman": """\
pac_col:     dc.b 0
pac_row:     dc.b 0
pac_dir:     dc.b 1
pac_nextdir: dc.b 1
gh_col:      dc.b 0,0
gh_row:      dc.b 0,0
gh_dir:      dc.b 0,0
gh_mode:     dc.b 0,0
pm_score:    dc.w 0
pm_lives:    dc.b 3
pm_level:    dc.b 1
pm_dots:     dc.w 0
pm_state:    dc.b 0
pm_fright:   dc.b 0
pm_mode:     dc.b 0
pm_modet:    dc.b 0
pm_subtick:  dc.b 0
pm_stepctr:  dc.b 0
pm_rng:      dc.b 1
""",
    "music": """\
mus_idx:     dc.b 0
""",
    "tracker": """\
tk_row:      dc.b 0
tk_chan:     dc.b 0
tk_top:      dc.b 0
tk_vis:      dc.b 0
tk_cur:      dc.b 0
tk_ch:       dc.b 0
tk_cellbuf:  dc.b 0,0,0,0,0,0
""",
    "paint": """\
pt_cx:       dc.b 0
pt_cy:       dc.b 0
pt_tool:     dc.b 0
pt_ink:      dc.b 3
pt_anchor:   dc.b 0
pt_ax:       dc.b 0
pt_ay:       dc.b 0
pt_outline:  dc.b 0
pt_target:   dc.b 0
pt_sp:       dc.b 0
pt_px:       dc.b 0
pt_py:       dc.b 0
pt_rx0:      dc.b 0
pt_rx1:      dc.b 0
pt_ry0:      dc.b 0
pt_ry1:      dc.b 0
pt_rx:       dc.b 0
pt_ry:       dc.b 0
""",
    "outlast": """\
ol_carx:     dc.b 0
ol_scroll:   dc.b 0
ol_dist:     dc.w 0
ol_crash:    dc.b 0
ol_b:        dc.b 0
ol_band:     dc.b 0
ol_bandy:    dc.b 0
ol_bc:       dc.b 0
ol_bhw:      dc.b 0
ol_bl:       dc.b 0
ol_br:       dc.b 0
""",
    # files+notepad share one binary; combined var block.
    "files_notepad": """\
files_sel:   dc.b 0
files_confirm: dc.b 0
note_idx:    dc.b 0
note_name:   dc.b 0,0,0,0,0,0,0,0,0,0,0,0
note_len:    dc.w 0
note_dirty:  dc.b 0
note_flash:  dc.b 0
np_active:   dc.b 0       ; 0 = Files view, 1 = Notepad view (internal mode)
""",
}

# tick entry per app (label in the .i body, or "rts" for a static app).
TICK = {
    "theme": "app_tick_rts", "music": "app_tick_rts", "tracker": "app_tick_rts", "paint": "app_tick_rts",
    "dostris": "dostris_tick", "pacman": "pacman_tick", "outlast": "ol_tick",
    "files_notepad": "app_tick_rts",
}

# Messages that used to live in the kernel string table but are only used by
# Files/Notepad - carried in that binary now.
FILES_MSGS = """\
msg_files_title:   dc.b "Files",0
msg_notepad_title: dc.b "Notepad: ",0
msg_files_help:    dc.b "RET=Open  D=Delete  R=Rescan  ESC=Back",0
msg_files_empty:   dc.b "(no files)",0
msg_confirm1:      dc.b "Delete ",0
msg_confirm2:      dc.b "? (Y/N)",0
msg_note_help:     dc.b "  ^S=Save  ESC=Back",0
msg_ln:            dc.b "Ln:",0
msg_col:           dc.b "  Col:",0
msg_bytes:         dc.b "  Bytes:",0
msg_full:          dc.b "  FULL",0
msg_saved:         dc.b "  SAVED",0
"""

HEADER = """\
; ============================================================================
; UnoDOS/AppleII %(name)s - DISK-LOADED app (generated by mkapps.py from
; %(src)s). Assembled at APP_BASE ($6000), loaded on demand by the kernel's
; launch_app, linked to the kernel only by the addresses in kernel_api.inc.
; First 3 bytes are a JMP to init, then JMP key (+3) and JMP tick (+6).
; ============================================================================
        processor 6502
        include "sys.inc"
        include "build/kernel_api.inc"

        org APP_BASE
        jmp %(init)s
        jmp %(key)s
        jmp %(tick)s
app_tick_rts:
        rts
"""


def strip_lifecycle(body, app):
    """Remove the <app>_open and <app>_close definitions from a .i body; we
    replace them with the ABI init/exit. Returns (body_without_them, open_body).
    open_body = the lines between <app>_open: and the next label, minus the
    `sta app_mode` / `lda #<mode>` / `jsr beep_click` lines (the kernel's
    launch_app already set app_mode + beeped)."""
    lines = body.split("\n")
    out, open_body = [], []
    i = 0
    n = len(lines)
    while i < n:
        ln = lines[i]
        m = re.match(r"^(\w+)_(open|close):", ln)
        if m and m.group(1) == app:
            kind = m.group(2)
            # consume until the next top-level label (col 0, ends with ':') or
            # blank-line-separated comment header of the next routine
            j = i + 1
            blk = []
            while j < n:
                if re.match(r"^\w+:", lines[j]):
                    break
                blk.append(lines[j])
                j += 1
            if kind == "open":
                open_body = blk
            i = j
            continue
        out.append(ln)
        i += 1
    return "\n".join(out), open_body


def make_init(app, open_body):
    """Build the <app>_init routine from the open body: drop the app_mode set,
    the `lda #<n>` that fed it, and the beep (kernel does both)."""
    kept = []
    skip_next_sta = False
    lines = list(open_body)
    out = []
    k = 0
    while k < len(lines):
        ln = lines[k]
        s = ln.strip()
        if s.startswith("sta app_mode"):
            # also drop the immediately-preceding `lda #..` that loaded it
            if out and out[-1].strip().startswith("lda #"):
                out.pop()
            k += 1
            continue
        if s.startswith("jsr beep_click"):
            k += 1
            continue
        out.append(ln)
        k += 1
    # alias <app>_open onto init so any internal restart jmp (e.g. OutLast's
    # crash-restart) still resolves to the setup+draw entry.
    init = ["%s_init:" % app, "%s_open:" % app] + out
    return "\n".join(init)


def gen_simple(app):
    src = app + ".i"
    body = open(os.path.join(HERE, src)).read()
    body, open_body = strip_lifecycle(body, app)
    if app == "music":
        # note_play moved into the kernel (exported via kernel_api.inc); drop
        # the app-local definition so it doesn't collide.
        body = strip_routine(body, "note_play")
    # ESC handlers branch to <app>_close (the old local close). Rewrite those
    # far branches to the inverse-branch-over-`jmp return_to_desktop` idiom.
    body = fix_far_branches(body, app + "_close")
    init = make_init(app, open_body)
    hdr = HEADER % dict(name=app, src=src, init=app + "_init",
                        key=app + "_key", tick=TICK[app])
    text = (hdr + "\n" + init + "\n" + body
            + "\n\n; ---- app state ----\n" + VARS[app])
    out = os.path.join(OUT, app + ".s")
    open(out, "w").write(text)
    return out


_INV = {"beq": "bne", "bne": "beq", "bcc": "bcs", "bcs": "bcc",
        "bmi": "bpl", "bpl": "bmi"}
_far_n = [0]


def fix_far_branches(body, close_label, dest="return_to_desktop"):
    """A relative branch to <close_label> can't reach the kernel routine the
    app exits through. Rewrite each `<branch> <close_label>` into the
    inverse-branch-over-`jmp <dest>` idiom so the long jump is absolute. Also
    rewrites a plain `jmp <close_label>` straight to `jmp <dest>`."""
    out = []
    for ln in body.split("\n"):
        m = re.match(r"^(\s*)(beq|bne|bcc|bcs|bmi|bpl)\s+%s\s*$"
                     % re.escape(close_label), ln)
        if m:
            ind, br = m.group(1), m.group(2)
            _far_n[0] += 1
            skip = "fx_%d" % _far_n[0]
            out.append("%s%s %s" % (ind, _INV[br], skip))
            out.append("%sjmp %s" % (ind, dest))
            out.append("%s:" % skip)
            continue
        m2 = re.match(r"^(\s*)jmp\s+%s\s*$" % re.escape(close_label), ln)
        if m2:
            out.append("%sjmp %s" % (m2.group(1), dest))
            continue
        out.append(ln)
    return "\n".join(out)


def strip_routine(body, name):
    """Remove a top-level routine `name:` and its body (up to the next label)."""
    lines = body.split("\n")
    out = []
    i = 0
    while i < len(lines):
        if re.match(r"^%s:" % re.escape(name), lines[i]):
            i += 1
            while i < len(lines) and not re.match(r"^\w+:", lines[i]):
                i += 1
            continue
        out.append(lines[i])
        i += 1
    return "\n".join(out)


def gen_files_notepad():
    """Files + Notepad share one binary. Internal view switch uses np_active
    instead of the old app_mode 1/2. init = files setup + files_draw. key =
    dispatch to files_key or notepad_key by np_active. tick = rts."""
    fbody = open(os.path.join(HERE, "files.i")).read()
    nbody = open(os.path.join(HERE, "notepad.i")).read()

    # --- Files: strip files_open/files_close; ESC branches to files_close
    #     (far) -> over-jmp to return_to_desktop ---
    fbody, fopen = strip_lifecycle(fbody, "files")
    fbody = fix_far_branches(fbody, "files_close")

    # --- Notepad: strip notepad_close (it jumped to files_draw / set app_mode=1)
    #     and rewrite notepad_load (sets app_mode=2) to set np_active=1. ---
    # notepad has notepad_close + notepad_load with app_mode writes.
    nlines = nbody.split("\n")
    nout = []
    i = 0
    while i < len(nlines):
        ln = nlines[i]
        if re.match(r"^notepad_close:", ln):
            # skip the close routine entirely (replaced by an np_close shim)
            i += 1
            while i < len(nlines) and not re.match(r"^\w+:", nlines[i]):
                i += 1
            continue
        nout.append(ln)
        i += 1
    nbody = "\n".join(nout)
    # notepad_load enters Notepad: replace `lda #2 / sta app_mode` with
    # `lda #1 / sta np_active`.
    nbody = nbody.replace("        lda #2\n        sta app_mode",
                          "        lda #1\n        sta np_active")
    # notepad's ESC went to notepad_close -> our np_close shim (a far local
    # label, so fix the relative branch into an over-jmp).
    nbody = re.sub(r"\bnotepad_close\b", "np_close", nbody)
    nbody = fix_far_branches(nbody, "np_close", dest="np_close")

    # init: files setup (minus app_mode/beep) + files view + files_draw
    finit = make_init("files", fopen)
    # finit's last line is `jmp files_draw`; ensure np_active=0 first.
    finit = finit.replace("files_init:",
                          "files_init:\n        lda #0\n        sta np_active")

    key_dispatch = """\
files_notepad_key:
        lda np_active
        beq fnk_files
        jmp notepad_key
fnk_files:
        jmp files_key

; np_close - ESC in Notepad: back to the Files view (np_active=0), redraw it.
np_close:
        lda #0
        sta np_active
        jmp files_draw
"""

    hdr = HEADER % dict(name="Files+Notepad", src="files.i + notepad.i",
                        init="files_init", key="files_notepad_key",
                        tick="app_tick_rts")
    text = (hdr + "\n" + finit + "\n\n" + key_dispatch + "\n"
            + fbody + "\n\n" + nbody
            + "\n\n; ---- app state ----\n" + VARS["files_notepad"]
            + "\n; ---- strings ----\n" + FILES_MSGS)
    out = os.path.join(OUT, "files_notepad.s")
    open(out, "w").write(text)
    return out


def main():
    os.makedirs(OUT, exist_ok=True)
    made = []
    for app in ["theme", "dostris", "pacman", "music", "tracker", "paint", "outlast"]:
        made.append(gen_simple(app))
    made.append(gen_files_notepad())
    for m in made:
        print("wrote", os.path.relpath(m, HERE))


if __name__ == "__main__":
    main()
