#!/usr/bin/env python3
"""Generate build/notes7.s - the Canon in D arrangement for the Apple II
speaker, plus the 12-pitch tone table.  Same arrangement as amiga/mkdata.py
(and apps/music.asm): 8 quarter notes then 16 eighth notes.

The Apple II has only the 1-bit $C030 speaker, toggled in a busy-wait loop
(see music.i note_play): a note is a (half-period delay constant, toggle
count) pair.  half = (cycles_per_half - NP_OVERHEAD) / 5, where
cycles_per_half = 1_000_000 / (2*freq).  A single-byte delay can't reach the
low octave (C4..F4 would need half>255), so playback is transposed UP ONE
OCTAVE (freq*2) - the speaker is tinny/high anyway.  The STAFF view keeps
the true (untransposed) note contour via yoff, so it reads as the real
arrangement; only the pitch is an octave up (documented deviation).

Emits, per note, 4 bytes: half, dur_lo, dur_hi, yoff.
"""
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "build", "notes7.s")

# untransposed pitch -> frequency (Hz) and MIDI number (for the staff yoff)
F = {"C4": 262, "D4": 294, "E4": 330, "F4": 349, "G4": 392, "A4": 440,
     "B4": 494, "C5": 523, "D5": 587, "E5": 659, "F5": 698, "G5": 784}
M = {"C4": 60, "D4": 62, "E4": 64, "F4": 65, "G4": 67, "A4": 69,
     "B4": 71, "C5": 72, "D5": 74, "E5": 76, "F5": 77, "G5": 79}

# Canon in D (same arrangement as apps/music.asm / amiga/mkdata.py)
QN_S, EN_S = 0.30, 0.15                       # quarter / eighth in seconds
tune = ([("C5", QN_S), ("B4", QN_S), ("A4", QN_S), ("G4", QN_S),
         ("F4", QN_S), ("E4", QN_S), ("F4", QN_S), ("G4", QN_S)]
        + [(n, EN_S) for n in ["C5", "E5", "B4", "D5", "A4", "C5", "G4", "B4",
                               "F4", "A4", "E4", "G4", "F4", "A4", "G4", "B4"]])

NP_OVERHEAD = 30          # fixed cycles per half-period outside the delay loop
HI_M = max(M.values())    # G5 = 79 -> top of the staff (yoff 0)
YSTEP = 3                 # pixels per semitone on the staff

rows = []
for name, dur_s in tune:
    freq2 = F[name] * 2                       # transpose up an octave
    half = round((1_000_000 / (2 * freq2) - NP_OVERHEAD) / 5)
    half = max(1, min(255, half))
    toggles = round(dur_s * freq2 * 2)        # one toggle per half-period
    toggles = max(1, min(65535, toggles))
    yoff = (HI_M - M[name]) * YSTEP            # higher pitch -> smaller yoff
    rows.append((half, toggles & 0xFF, toggles >> 8, yoff, name))

# ---- Tracker tone table: 24 semitones (C-2..B-3, ProTracker note 1..24) ----
# Mapped to an audible Apple-II range: note 1 = A4 (440 Hz), rising two
# octaves.  Each row sounds for TK_ROW_S seconds (toggles scale with freq so
# every row holds the same duration).
TK_BASE = 440.0
TK_ROW_S = 0.14
tk = []
for n in range(24):
    freq = TK_BASE * (2 ** (n / 12.0))
    half = round((1_000_000 / (2 * freq) - NP_OVERHEAD) / 5)
    half = max(1, min(255, half))
    toggles = max(1, min(65535, round(TK_ROW_S * freq * 2)))
    tk.append((half, toggles & 0xFF, toggles >> 8))

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", newline="\n") as f:
    f.write("; generated by mknotes.py - Canon in D + Tracker tone table, "
            "Apple II speaker (octave up). do not edit\n")
    f.write("mus_count: dc.b %d\n" % len(rows))
    f.write("; per note: half-period delay, toggle count (lo,hi), staff yoff\n")
    f.write("mus_notes:\n")
    for half, dlo, dhi, yoff, name in rows:
        f.write("\tdc.b %3d,%3d,%3d,%3d  ; %s\n" % (half, dlo, dhi, yoff, name))
    f.write("\n; Tracker: 24 semitones, ProTracker note 1..24 -> index 0..23\n")
    f.write("tk_half:  dc.b " + ",".join("%d" % h for h, _, _ in tk) + "\n")
    f.write("tk_durlo: dc.b " + ",".join("%d" % d for _, d, _ in tk) + "\n")
    f.write("tk_durhi: dc.b " + ",".join("%d" % d for _, _, d in tk) + "\n")
print("wrote %s: %d music notes, %d tracker semitones" % (OUT, len(rows), len(tk)))
