#!/usr/bin/env python3
"""Export the shared UnoDOS 8x8 font (amiga/gen_data.i font8x8) to a C array
header for the Dreamcast port's software framebuffer text primitive.

The shared font is 95 glyphs (ASCII 32..126), 8 bytes/glyph, one byte per
pixel row, bit 7 = leftmost pixel (the 68K MSB-left convention every other
port consumes). We emit it verbatim as uno_font8x8[95][8]; fb_text() shifts
bit 7 down to the leftmost screen pixel, so no bit reversal here.

Reads ../amiga/gen_data.i (run amiga/mkdata.py first - build.sh does),
writes build/font_data.h.
"""
import re, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "amiga", "gen_data.i")
OUT = os.path.join(HERE, "build", "font_data.h")

text = open(SRC).read()
m = re.search(r"font8x8:\n((?:\s+dc\.b[^\n]+\n)+)", text)
if not m:
    sys.exit("font8x8 block not found in gen_data.i")
rows = [int(t, 16) for t in re.findall(r"\$([0-9A-Fa-f]{2})", m.group(1))]
nglyph = min(len(rows) // 8, 95)

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w", newline="\n") as f:
    f.write("/* generated by dreamcast/mkfont_c.py from the shared UnoDOS font - "
            "do not edit.\n")
    f.write("   95 glyphs, ASCII 32..126, 8 bytes/glyph, bit7 = leftmost "
            "pixel. */\n")
    f.write("#ifndef UNO_FONT_DATA_H\n#define UNO_FONT_DATA_H\n\n")
    f.write("#define UNO_FONT_FIRST 32\n")
    f.write("#define UNO_FONT_COUNT %d\n\n" % nglyph)
    f.write("static const unsigned char uno_font8x8[%d][8] = {\n" % nglyph)
    for g in range(nglyph):
        b = rows[g * 8:g * 8 + 8]
        ch = g + 32
        cc = chr(ch) if 33 <= ch <= 126 else " "
        f.write("    {%s}, /* %3d '%s' */\n"
                % (",".join("0x%02X" % x for x in b), ch, cc))
    f.write("};\n\n#endif\n")
print("wrote %s: %d glyphs" % (OUT, nglyph))
